/**
 * Cardinality on the canonical predicate, against a real Postgres (#5027,
 * ADR-0037 §3).
 *
 * ADR-0037 §9 (T7) names three falsification targets for this slice, and every
 * one of them **passes green if the change is absent** — which is the whole
 * reason they are here rather than in the unit suites:
 *
 *   **(a) two facts in one slot supersede REGARDLESS of what the extractor
 *   guessed.** Today's fixtures cannot catch the stochastic failure because they
 *   hand-write BOTH cardinalities — the agree-by-construction trap wearing a
 *   different hat. This suite writes the two sides with DELIBERATELY OPPOSITE
 *   guesses and asserts the collision fires anyway, which is exactly the state
 *   the old both-sides clause refused.
 *
 *   **(b) an UNCURATED predicate never supersedes.** Absent from the vocabulary
 *   means `multi`, so the same pair with no entry must collide zero times. This
 *   is the positive-evidence rule, and without it the test above is satisfied by
 *   a build that simply deleted the guard.
 *
 *   **(c) a TYPO CORRECTION does not propose `single`.** A reviewer fixing
 *   `Bob` → `Bobby` is not asserting single-valuedness, and ADR-0037 §3(d)
 *   carries this as the known weak point of source 2 rather than claiming to
 *   have designed it away. What stands between a typo and a spurious proposal is
 *   two arms, and the second is the one only real Postgres can exercise: the
 *   repeat gate counts DISTINCT SUBJECTS, and it counts only supersessions whose
 *   replacement is PROVABLY DIFFERENT from what it replaced
 *   (`comparableDifferentSql`, #5030). Two entity-valued names are `unknown`,
 *   never *different*, so the pair does not count.
 *
 * ## Why the doubles cannot own any of this
 *
 * All three turn on statements rather than on control flow: a correlated EXISTS
 * against a table, and a `COUNT(DISTINCT …)` whose selectivity comes from an
 * `object_cmp` arm no in-memory fake has values for. A double that scripted
 * those answers would be asserting its own script — #5000's trap, which is what
 * this whole map exists to remove. `correction.test.ts` owns the WIRING (which
 * verbs feed the gate, what a proposal carries, that it is only ever a
 * proposal); this file owns whether the rules are true.
 *
 * Opt in locally with the same scratch database as its sibling brain suites —
 * every one of them creates and drops its OWN schema, so they share it safely:
 *   bun run db:up && export TEST_DATABASE_URL=postgresql://atlas:atlas@localhost:5433/brain_4771_scratch
 *
 * ## MUTATIONS THIS CATCHES
 *
 * `scripts/mutations/cardinality.md`, GENERATED by `scripts/mutate.ts` from
 * `scripts/mutations/cardinality.mutations.ts` — never hand-measured (#5060).
 * Regenerate with:
 *   cd packages/api && bun run scripts/mutate.ts scripts/mutations/cardinality.mutations.ts
 *
 * Two cells there are the ones to read, and both are in THIS file's column:
 * restoring the both-sides clause, and dropping `status = 'approved'` from the
 * one live read. Each looks like a tightening in a diff, and neither has any
 * symptom at rest.
 */

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { Pool } from "pg";
import { runMigrations } from "@atlas/api/lib/db/migrate";
import { MANAGED_AUTH_MIGRATIONS, _resetPool } from "@atlas/api/lib/db/internal";
import {
  CARDINALITY_HELD_BACK_COUNT_SQL,
  supersedingDraftPredicate,
  supersessionCollisionPredicate,
} from "@atlas/api/lib/content-mode/adapters/brain-facts";
import { identityAlias, identityVocabulary, slotKey } from "@atlas/api/lib/brain/identity";
import {
  CORRECTION_EVENT_PRODUCER,
  CORRECTION_REPEAT_THRESHOLD,
  declarePredicateCardinality,
  decidePredicateCardinality,
  decidePredicateCardinalityForSurface,
  proposeFromCorrectionEvents,
  proposePredicateCardinality,
  readPredicateCardinality,
} from "@atlas/api/lib/brain/cardinality";
import { comparableValue } from "@atlas/api/lib/brain/object-cmp";
import { HUMAN_SOURCE } from "@atlas/api/lib/brain/sources";

const TEST_DB_URL = process.env.TEST_DATABASE_URL;
const describeIfPg = TEST_DB_URL ? describe : describe.skip;
const PG_TEST_TIMEOUT_MS = 60_000;

describeIfPg("cardinality on the canonical predicate (#5027)", () => {
  let pool: Pool;
  let priorDatabaseUrl: string | undefined;
  const schemaName = `brain_5027_${Date.now()}_${Math.floor(Math.random() * 1e6)}`;

  beforeAll(async () => {
    priorDatabaseUrl = process.env.DATABASE_URL;
    process.env.DATABASE_URL = TEST_DB_URL;
    pool = new Pool({
      connectionString: TEST_DB_URL,
      options: `-c search_path="${schemaName}",public`,
    });
    const bootstrap = new Pool({ connectionString: TEST_DB_URL });
    try {
      await bootstrap.query(`CREATE SCHEMA IF NOT EXISTS "${schemaName}"`);
    } finally {
      await bootstrap.end();
    }
    await runMigrations(pool, { skip: MANAGED_AUTH_MIGRATIONS });
    _resetPool(pool);
  }, PG_TEST_TIMEOUT_MS);

  afterAll(async () => {
    _resetPool(null);
    if (priorDatabaseUrl === undefined) delete process.env.DATABASE_URL;
    else process.env.DATABASE_URL = priorDatabaseUrl;
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`);
      await pool.end();
    }
  }, PG_TEST_TIMEOUT_MS);

  // -------------------------------------------------------------------------
  // Fixtures
  // -------------------------------------------------------------------------

  async function seedEpisode(workspaceId: string, sourceId: string, source = "slack") {
    const { rows } = await pool.query<{ id: string }>(
      `INSERT INTO brain_episodes
         (workspace_id, source, source_id, source_actor, body, occurred_at, visible_to)
       VALUES ($1, $2, $3, 'U123', 'evidence', now(), ARRAY['org'])
       RETURNING id`,
      [workspaceId, source, sourceId],
    );
    return rows[0]!.id;
  }

  /**
   * A fact inserted DIRECTLY, with its row-level `predicate_cardinality` stated
   * explicitly.
   *
   * The direct insert is the point rather than a shortcut. `INSERT_FACT_SQL` no
   * longer binds that column at all, so the production path cannot produce the
   * DISAGREEING pair target (a) needs — the two sides would both fall to the
   * schema default and the fixture would agree with itself, which is precisely
   * the failure mode #5000 was built out of. Writing the column by hand is the
   * only way to stand up the state the old both-sides clause used to refuse.
   */
  async function seedFact(
    workspaceId: string,
    episodeId: string,
    claim: { subject: string; predicate: string; object: string },
    opts: { status: "draft" | "published"; rowCardinality: "single" | "multi" },
  ): Promise<string> {
    const cmp = comparableValue({ surface: claim.object });
    const { rows } = await pool.query<{ id: string }>(
      `INSERT INTO brain_facts
         (workspace_id, subject, predicate, object, source_episode_id, provenance,
          visible_to, status, predicate_cardinality,
          subject_key, predicate_key, object_key, object_cmp)
       VALUES ($1, $2, $3, $4, $5, '{"source":"slack","actor":"test"}'::jsonb, ARRAY['org'],
               $6, $7, $8, $9, $10, $11)
       RETURNING id`,
      [
        workspaceId,
        claim.subject,
        claim.predicate,
        claim.object,
        episodeId,
        opts.status,
        opts.rowCardinality,
        slotKey(claim.subject, identityAlias),
        slotKey(claim.predicate, identityAlias),
        slotKey(claim.object, identityAlias),
        cmp,
      ],
    );
    return rows[0]!.id;
  }

  /**
   * How many published rivals the workspace's promotable drafts would supersede
   * — the shipped predicate, imported rather than restated.
   *
   * Restating it would make this suite a second spelling of "what collides",
   * which `supersessionCollisionJoin`'s own header forbids at length: a
   * disclosure that lists one set while the transaction stamps another.
   */
  async function collisionCount(workspaceId: string): Promise<number> {
    const { rows } = await pool.query<{ n: string }>(
      `SELECT count(*)::text AS n
         FROM brain_facts d
         JOIN brain_facts p ON ${supersessionCollisionPredicate("d", "p")}
        WHERE d.workspace_id = $1 AND ${supersedingDraftPredicate("d")}`,
      [workspaceId],
    );
    return Number(rows[0]!.n);
  }

  /** Approve a canonical predicate as `single`, through the shipped door. */
  async function curate(workspaceId: string, predicate: string, cardinality: "single" | "multi") {
    const result = await declarePredicateCardinality(pool, workspaceId, {
      predicateKey: slotKey(predicate, identityAlias),
      cardinality,
      authoredBy: "curator-1",
    });
    expect(result.ok, `curating "${predicate}" failed — the assertions below are vacuous`).toBe(
      true,
    );
  }

  // -------------------------------------------------------------------------
  // Target (a) — the extractor's guess no longer decides
  // -------------------------------------------------------------------------

  describe("target (a): two facts in one slot supersede regardless of the extractor's guess", () => {
    it(
      "collides when the two rows DISAGREE about cardinality — the state the old clause refused",
      async () => {
        const ws = "ws-5027-disagree";
        const ep = await seedEpisode(ws, "a-disagree");
        // The published side says `multi`, the draft says `single`. Under the
        // deleted clause this pair could not collide, and NOTHING about the
        // claims themselves justified that — the two values came from two
        // independent model calls on two different messages.
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "499 USD" },
          { status: "published", rowCardinality: "multi" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "599 USD" },
          { status: "draft", rowCardinality: "single" },
        );
        await curate(ws, "priced at", "single");

        expect(
          await collisionCount(ws),
          "the collision did not fire for a pair whose ROWS disagree about cardinality — the both-sides clause is back, and with it a supersession gate that fires at roughly P(model says `single`)²",
        ).toBe(1);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "…and when BOTH rows say `multi`, which is what every un-hinted row now carries",
      async () => {
        // The case that matters in production, and the one the disagreeing pair
        // above does not cover. `INSERT_FACT_SQL` stopped binding the column, so
        // every row written since this slice falls to the schema default
        // `'multi'` — meaning a build that kept the clause but read only ONE
        // side would still supersede nothing, forever, with no error anywhere.
        const ws = "ws-5027-both-multi";
        const ep = await seedEpisode(ws, "a-both-multi");
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "499 USD" },
          { status: "published", rowCardinality: "multi" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "599 USD" },
          { status: "draft", rowCardinality: "multi" },
        );
        await curate(ws, "priced at", "single");

        expect(await collisionCount(ws)).toBe(1);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "…and does NOT collide when both rows say `single` but the predicate is uncurated",
      async () => {
        // The inverse control, and the one that proves the two tests above are
        // reading the vocabulary rather than having simply deleted a guard. Both
        // rows carry the strongest possible row-level claim; it buys nothing,
        // because the row is no longer where the question is asked.
        const ws = "ws-5027-both-single-uncurated";
        const ep = await seedEpisode(ws, "a-both-single");
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "499 USD" },
          { status: "published", rowCardinality: "single" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "599 USD" },
          { status: "draft", rowCardinality: "single" },
        );

        expect(
          await collisionCount(ws),
          "a pair with `single` on both ROWS superseded with no vocabulary entry — the row column is load-bearing again, which is the defect #5027 removed",
        ).toBe(0);
      },
      PG_TEST_TIMEOUT_MS,
    );
  });

  // -------------------------------------------------------------------------
  // Target (b) — `single` requires positive evidence
  // -------------------------------------------------------------------------

  describe("target (b): an uncurated predicate never supersedes", () => {
    it(
      "absent from the vocabulary means `multi`",
      async () => {
        const ws = "ws-5027-uncurated";
        const ep = await seedEpisode(ws, "b-uncurated");
        await seedFact(
          ws,
          ep,
          { subject: "acme", predicate: "reports to", object: "499 USD" },
          { status: "published", rowCardinality: "single" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "acme", predicate: "reports to", object: "599 USD" },
          { status: "draft", rowCardinality: "single" },
        );

        expect(await collisionCount(ws)).toBe(0);

        // The positive control, in the SAME workspace and on the SAME rows:
        // curating the predicate is the only thing that changes, and the
        // collision appears. Without it "0" is satisfied by a fixture whose
        // objects were never provably different in the first place.
        await curate(ws, "reports to", "single");
        expect(await collisionCount(ws)).toBe(1);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "an entry licenses ONE predicate, not the workspace",
      async () => {
        // The `c.predicate_key = d.predicate_key` arm, falsified behaviourally
        // rather than lexically. Without it a single curated predicate would
        // license supersession across every slot in the tenant — the entry would
        // be a property of the WORKSPACE rather than of the predicate, which is
        // the one reading of "read live" that would be catastrophic.
        const ws = "ws-5027-one-predicate";
        const ep = await seedEpisode(ws, "b-scope");
        // The curated predicate, with a pair that must collide.
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "499 USD" },
          { status: "published", rowCardinality: "multi" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "priced at", object: "599 USD" },
          { status: "draft", rowCardinality: "multi" },
        );
        // An UNCURATED predicate in the same workspace, whose pair is otherwise
        // identical in every way the collision looks at — same subject slot
        // shape, provably different comparable objects, published rival live and
        // current. The ONLY difference is which predicate it is.
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "renews on", object: "700 USD" },
          { status: "published", rowCardinality: "multi" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "business tier", predicate: "renews on", object: "800 USD" },
          { status: "draft", rowCardinality: "multi" },
        );
        await curate(ws, "priced at", "single");

        expect(
          await collisionCount(ws),
          "curating ONE predicate licensed supersession for another — `cardinalitySingleSql` lost its `predicate_key` arm, so an entry now speaks for the whole workspace",
        ).toBe(1);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "an explicit `multi` entry does not supersede either — ambiguity resolves down",
      async () => {
        // ADR-0037 §3(b): a predicate whose cardinality depends on the subject's
        // type (`located in` — one HQ, many offices) is never marked `single`,
        // so it never has to be adjudicated. A stored `multi` is a human
        // DECLINING the question, and it must behave exactly like absence at the
        // gate while behaving differently at the proposer.
        const ws = "ws-5027-explicit-multi";
        const ep = await seedEpisode(ws, "b-multi");
        await seedFact(
          ws,
          ep,
          { subject: "acme", predicate: "located in", object: "499 USD" },
          { status: "published", rowCardinality: "single" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "acme", predicate: "located in", object: "599 USD" },
          { status: "draft", rowCardinality: "single" },
        );
        await curate(ws, "located in", "multi");

        expect(await collisionCount(ws)).toBe(0);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "a PENDING `single` proposal does not supersede — only an approved entry does",
      async () => {
        // The arm that keeps a repeat-gated heuristic from stamping `valid_to`
        // with no human in the loop. Deleting `c.status = 'approved'` from
        // `cardinalitySingleSql` is a one-token change that looks like a
        // simplification and hands the producer the irreversible write.
        const ws = "ws-5027-pending";
        const ep = await seedEpisode(ws, "b-pending");
        await seedFact(
          ws,
          ep,
          { subject: "acme", predicate: "owned by", object: "499 USD" },
          { status: "published", rowCardinality: "single" },
        );
        await seedFact(
          ws,
          ep,
          { subject: "acme", predicate: "owned by", object: "599 USD" },
          { status: "draft", rowCardinality: "single" },
        );
        const proposed = await proposePredicateCardinality(pool, ws, {
          predicateKey: slotKey("owned by", identityAlias),
          cardinality: "single",
          sourceClass: "correction_event",
          proposedBy: CORRECTION_EVENT_PRODUCER,
        });
        expect(proposed.ok, "the proposal was refused — the assertion below is vacuous").toBe(true);

        expect(
          await collisionCount(ws),
          "a PENDING proposal made a published belief supersedable — `cardinalitySingleSql` stopped filtering on `approved`, so a producer now decides an irreversible write",
        ).toBe(0);

        // The control: approving the same row, and nothing else, fires it.
        expect(
          await decidePredicateCardinality(pool, ws, slotKey("owned by", identityAlias)!, "approved", "curator-1"),
        ).toBe(true);
        expect(await collisionCount(ws)).toBe(1);
      },
      PG_TEST_TIMEOUT_MS,
    );
  });

  // -------------------------------------------------------------------------
  // The write-path allowlist
  // -------------------------------------------------------------------------

  describe("the write path admits three sources and no others", () => {
    it(
      "a producer may not propose `multi` — it asserts nothing and occupies the slot",
      async () => {
        const ws = "ws-5027-producer-multi";
        // Cast, deliberately: `CardinalityProposalInput.cardinality` is
        // narrowed to `"single"`, so a typed caller CANNOT reach this refusal —
        // which is the stronger half of the guarantee and is checked by the
        // compiler. What this test covers is the other half: an untyped caller
        // (a cast, `JSON.parse`, a future producer reading config) is still
        // refused at runtime rather than occupying the predicate's only slot.
        const result = await proposePredicateCardinality(pool, ws, {
          predicateKey: slotKey("reports to", identityAlias),
          cardinality: "multi" as "single",
          sourceClass: "correction_event",
          proposedBy: CORRECTION_EVENT_PRODUCER,
        });
        expect(result).toMatchObject({ ok: false, refusal: "producer-proposed-multi" });
        // And nothing landed, so the `single` proposal that DOES carry
        // information is still possible.
        expect(await readPredicateCardinality(pool, ws, slotKey("reports to", identityAlias)!)).toBeNull();
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "a REJECTED entry is permanent memory — the producer cannot re-propose over it",
      async () => {
        // #4507's rejection memory, on 0190's terms: the rejected row occupies
        // the predicate's only slot, so the refusal is structural rather than a
        // race between a SELECT and an INSERT. Without it the producer re-writes
        // what a human declined on its very next run.
        const ws = "ws-5027-rejection-memory";
        const key = slotKey("reports to", identityAlias)!;
        await proposePredicateCardinality(pool, ws, {
          predicateKey: key,
          cardinality: "single",
          sourceClass: "correction_event",
          proposedBy: CORRECTION_EVENT_PRODUCER,
        });
        expect(await decidePredicateCardinality(pool, ws, key, "rejected", "curator-1")).toBe(true);

        const again = await proposePredicateCardinality(pool, ws, {
          predicateKey: key,
          cardinality: "single",
          sourceClass: "correction_event",
          proposedBy: CORRECTION_EVENT_PRODUCER,
        });
        expect(again).toMatchObject({ ok: false, refusal: "already-decided" });
        expect(await readPredicateCardinality(pool, ws, key)).toMatchObject({ status: "rejected" });
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "a human may still author over a rejection — the memory binds PRODUCERS",
      async () => {
        // The asymmetry is the authority posture, not an inconsistency: a
        // rejection is this workspace's own decision, and the gate exists so a
        // person can change it. Without this arm a mistaken rejection would make
        // a predicate permanently un-curatable.
        const ws = "ws-5027-human-override";
        const key = slotKey("reports to", identityAlias)!;
        await proposePredicateCardinality(pool, ws, {
          predicateKey: key,
          cardinality: "single",
          sourceClass: "correction_event",
          proposedBy: CORRECTION_EVENT_PRODUCER,
        });
        await decidePredicateCardinality(pool, ws, key, "rejected", "curator-1");

        await curate(ws, "reports to", "single");
        expect(await readPredicateCardinality(pool, ws, key)).toMatchObject({
          status: "approved",
          cardinality: "single",
          sourceClass: "human",
        });
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "the author column is enforced by the DATABASE too — `NOT NULL` alone admits `''`",
      async () => {
        // The write paths refuse it, but they are not the only writer this table
        // will have: #5025's route and #5042's producer are still to come, and a
        // CHECK is what holds for a hand-written INSERT or a region importer. An
        // approved `single` row with no author supersedes at the gate — which
        // never reads `proposed_by` — while `readPredicateCardinality` reports
        // it absent, so the row is load-bearing and invisible at once.
        const ws = "ws-5027-author-check";
        await expect(
          pool.query(
            `INSERT INTO brain_predicate_cardinality
               (workspace_id, predicate_key, cardinality, status, source_class, proposed_by)
             VALUES ($1, 'reports to', 'single', 'approved', 'human', '')`,
            [ws],
          ),
        ).rejects.toThrow(/ck_brain_predicate_cardinality_author_present/);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "the source-class allowlist is enforced by the DATABASE, not only by the caller",
      async () => {
        // ADR-0037 §3(d) names three sources and no others, and a fourth
        // producer must earn its arm in a migration rather than inherit one. The
        // CHECK is what makes that true of a hand-written INSERT and of the
        // region importer, neither of which goes through this module.
        const ws = "ws-5027-check";
        await expect(
          pool.query(
            `INSERT INTO brain_predicate_cardinality
               (workspace_id, predicate_key, cardinality, status, source_class, proposed_by)
             VALUES ($1, 'reports to', 'single', 'approved', 'extractor', 'someone')`,
            [ws],
          ),
        ).rejects.toThrow(/ck_brain_predicate_cardinality_source_class/);
      },
      PG_TEST_TIMEOUT_MS,
    );
  });

  // -------------------------------------------------------------------------
  // Target (c) — the repeat gate, and the typo it must not read as evidence
  // -------------------------------------------------------------------------

  describe("target (c): the correction-event repeat gate", () => {
    /**
     * One human supersession at `predicate`, for `subject`: the replacement
     * fact, the retired fact, the `supersedes` edge, and a HUMAN episode behind
     * the replacement. Exactly the residue `correction.ts`'s supersede verb
     * leaves, assembled here so the gate can be measured over many subjects
     * without running the verb dozens of times.
     */
    async function seedSupersession(
      workspaceId: string,
      subject: string,
      predicate: string,
      from: string,
      to: string,
    ): Promise<void> {
      const humanEpisode = await seedEpisode(
        workspaceId,
        `corr-${subject}-${to}`,
        HUMAN_SOURCE,
      );
      const slackEpisode = await seedEpisode(workspaceId, `src-${subject}-${from}`);
      const oldId = await seedFact(
        workspaceId,
        slackEpisode,
        { subject, predicate, object: from },
        { status: "published", rowCardinality: "multi" },
      );
      const newId = await seedFact(
        workspaceId,
        humanEpisode,
        { subject, predicate, object: to },
        { status: "published", rowCardinality: "multi" },
      );
      await pool.query(
        `INSERT INTO brain_edges (workspace_id, edge_type, from_fact_id, to_fact_id)
         VALUES ($1, 'supersedes', $2::uuid, $3::uuid)`,
        [workspaceId, newId, oldId],
      );
    }

    it(
      "proposes `single` once enough DISTINCT subjects have been superseded",
      async () => {
        const ws = "ws-5027-gate-fires";
        const key = slotKey("priced at", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD; i++) {
          await seedSupersession(ws, `tier-${i}`, "priced at", `${100 + i} USD`, `${200 + i} USD`);
        }

        expect(await proposeFromCorrectionEvents(pool, ws, key)).toBe(true);
        expect(await readPredicateCardinality(pool, ws, key)).toMatchObject({
          cardinality: "single",
          // PENDING. A repeat gate is circumstantial evidence, and the write it
          // would license is retroactive across every published pair in the
          // slot — so it proposes and a human decides.
          status: "pending",
          sourceClass: "correction_event",
        });
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "stays silent one subject short — the threshold is real",
      async () => {
        const ws = "ws-5027-gate-short";
        const key = slotKey("priced at", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD - 1; i++) {
          await seedSupersession(ws, `tier-${i}`, "priced at", `${100 + i} USD`, `${200 + i} USD`);
        }

        expect(await proposeFromCorrectionEvents(pool, ws, key)).toBe(false);
        expect(await readPredicateCardinality(pool, ws, key)).toBeNull();
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "counts DISTINCT SUBJECTS, not corrections — a reviewer editing ONE slot proves nothing",
      async () => {
        // A correction event is evidence about a PREDICATE, and only variety
        // across subjects makes it that. Someone correcting one slot repeatedly
        // has most likely been fixing their own typing, and counting corrections
        // would make the loudest evidence the least informative kind.
        const ws = "ws-5027-gate-one-subject";
        const key = slotKey("priced at", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD + 3; i++) {
          await seedSupersession(ws, "business tier", "priced at", `${100 + i} USD`, `${200 + i} USD`);
        }

        expect(
          await proposeFromCorrectionEvents(pool, ws, key),
          "the repeat gate counted CORRECTIONS rather than distinct subjects — a typo dance in one slot now proposes a workspace-wide `single`, which makes every published pair at that predicate destructively collidable",
        ).toBe(false);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "a TYPO CORRECTION does not propose `single` — the named weak point, measured",
      async () => {
        // ADR-0037 §3(d)'s carried risk: `Bob` → `Bobby` is a reviewer fixing a
        // name, not asserting that a person has one manager, and the correction
        // verb is the SAME verb either way. Nothing in the event distinguishes
        // them.
        //
        // What does the work is the provable-difference arm. Two entity-valued
        // names have no comparable value on either side (there is no entity
        // store — `passthroughEntityResolver` is the shipped default), so
        // `comparableDifferentSql` is false and the pair is not counted. Three
        // typo corrections across three DISTINCT subjects — the strongest shape
        // the typo case can take — still propose nothing.
        const ws = "ws-5027-typo";
        const key = slotKey("reports to", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD + 2; i++) {
          await seedSupersession(ws, `person-${i}`, "reports to", "Bob", "Bobby");
        }

        expect(
          await proposeFromCorrectionEvents(pool, ws, key),
          "a run of typo corrections proposed `single` — the repeat gate lost its provable-difference arm, and #5027's known weak point is now live",
        ).toBe(false);
        expect(await readPredicateCardinality(pool, ws, key)).toBeNull();
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "…and the same shape with COMPARABLE objects DOES propose — the positive control",
      async () => {
        // Its own `it()`, sharing nothing with the prohibition above: in a long
        // proof the first failure hides the rest, and a positive control that
        // broke would silently license the test it exists to license. Every
        // assertion in the typo test is satisfied by a gate that proposes
        // nothing, ever.
        //
        // It is also where the ACCEPTED residual is visible: what separates this
        // from the typo case is the OBJECT TYPE, not the intent. A fat-finger on
        // a comparable value — `499` → `4999` — is provably different and counts.
        // That is a proposal, a human reads it, and that is the whole mitigation.
        const ws = "ws-5027-typo-control";
        const key = slotKey("reports to", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD; i++) {
          await seedSupersession(ws, `person-${i}`, "reports to", "499 USD", "599 USD");
        }

        expect(await proposeFromCorrectionEvents(pool, ws, key)).toBe(true);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "counts only HUMAN supersessions — the publish gate's own edges are not evidence",
      async () => {
        // The publish gate writes `supersedes` edges too. Counting those would
        // close the loop on itself: an approved `single` produces edges, the
        // edges re-propose `single`, and the gate would report a workspace's own
        // automated arbitrations back to it as human evidence.
        //
        // Unreachable TODAY — the publish gate needs an approved entry that by
        // definition does not exist before the first proposal — which is exactly
        // why it needs a test: it becomes reachable the moment one is approved,
        // and nothing else would notice.
        const ws = "ws-5027-gate-machine";
        const key = slotKey("priced at", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD + 2; i++) {
          const machineEpisode = await seedEpisode(ws, `publish-${i}`, "slack");
          const oldId = await seedFact(
            ws,
            machineEpisode,
            { subject: `tier-${i}`, predicate: "priced at", object: `${100 + i} USD` },
            { status: "published", rowCardinality: "multi" },
          );
          const newId = await seedFact(
            ws,
            machineEpisode,
            { subject: `tier-${i}`, predicate: "priced at", object: `${200 + i} USD` },
            { status: "published", rowCardinality: "multi" },
          );
          await pool.query(
            `INSERT INTO brain_edges (workspace_id, edge_type, from_fact_id, to_fact_id)
             VALUES ($1, 'supersedes', $2::uuid, $3::uuid)`,
            [ws, newId, oldId],
          );
        }

        expect(
          await proposeFromCorrectionEvents(pool, ws, key),
          "the repeat gate counted the publish gate's own supersessions as human evidence — the system would then propose `single` from arbitrations it performed itself",
        ).toBe(false);
      },
      PG_TEST_TIMEOUT_MS,
    );

    it(
      "is scoped to ONE workspace",
      async () => {
        const ws = "ws-5027-gate-scope";
        const other = "ws-5027-gate-scope-other";
        const key = slotKey("priced at", identityAlias)!;
        for (let i = 0; i < CORRECTION_REPEAT_THRESHOLD + 2; i++) {
          await seedSupersession(other, `tier-${i}`, "priced at", `${100 + i} USD`, `${200 + i} USD`);
        }

        expect(await proposeFromCorrectionEvents(pool, ws, key)).toBe(false);
      },
      PG_TEST_TIMEOUT_MS,
    );
  });

  // -------------------------------------------------------------------------
  // The operator's trace: what curation would unlock
  // -------------------------------------------------------------------------

  it(
    "CARDINALITY_HELD_BACK_COUNT_SQL counts the pairs curation would make supersedable",
    async () => {
      // ⚠️ This statement runs behind `advisoryCount`'s savepoint and is
      // deliberately kept OUT of `PromotionReport`, so a failure degrades to
      // `null`, logs a warn, and the publish commits — which means a broken
      // statement is invisible to every publish-path suite. Verified: appending
      // `AND d.no_such_column = 1` left all four of them green.
      //
      // Its docstring calls it *required rather than nice to have*: it is the
      // only thing distinguishing "supersession stopped workspace-wide because
      // nothing is curated" from "the cardinality read is broken". A diagnostic
      // carrying that job with no test of even its EXECUTABILITY would ship dead
      // and produce exactly the ambiguity it was added to remove.
      //
      // Executed DIRECTLY here rather than observed through a log, which proves
      // executability and arithmetic in one pass and needs no logger mock in a
      // `-pg` suite.
      const ws = "ws-5027-held-back";
      const ep = await seedEpisode(ws, "held-back");
      const published = await seedFact(
        ws,
        ep,
        { subject: "business tier", predicate: "priced at", object: "499 USD" },
        { status: "published", rowCardinality: "multi" },
      );
      const draft = await seedFact(
        ws,
        ep,
        { subject: "business tier", predicate: "priced at", object: "599 USD" },
        { status: "draft", rowCardinality: "multi" },
      );
      // A SECOND slot at an unrelated predicate, so the count is a real
      // selection rather than "every promotable draft".
      await seedFact(
        ws,
        ep,
        { subject: "acme", predicate: "renews on", object: "700 USD" },
        { status: "published", rowCardinality: "multi" },
      );
      const other = await seedFact(
        ws,
        ep,
        { subject: "acme", predicate: "renews on", object: "800 USD" },
        { status: "draft", rowCardinality: "multi" },
      );

      const heldBack = async () => {
        const { rows } = await pool.query<{ held_back: number }>(CARDINALITY_HELD_BACK_COUNT_SQL, [
          ws,
          [draft, other],
        ]);
        return rows[0]!.held_back;
      };

      // Nothing curated: BOTH provable collisions are held back, and the number
      // is what tells an operator there is something to curate.
      expect(await heldBack()).toBe(2);
      expect(await collisionCount(ws)).toBe(0);
      void published;

      // Curating ONE predicate moves exactly one pair from held-back to
      // stamped. The two numbers partition, which is the property the
      // statement's docstring claims and the only way to read either safely.
      await curate(ws, "priced at", "single");
      expect(await heldBack()).toBe(1);
      expect(await collisionCount(ws)).toBe(1);

      await curate(ws, "renews on", "single");
      expect(await heldBack()).toBe(0);
      expect(await collisionCount(ws)).toBe(2);
    },
    PG_TEST_TIMEOUT_MS,
  );

  it(
    "…and does NOT count a pair the TIER guard blocks — the two diagnostics partition",
    async () => {
      // The named gap in the statement's own docstring, asserted rather than
      // left as prose: a pair blocked by BOTH cardinality and tier appears in
      // neither count, deliberately, because reporting it as "curate this and it
      // will supersede" would be false — the tier refusal is permanent.
      const ws = "ws-5027-held-back-tier";
      const ep = await seedEpisode(ws, "held-back-tier");
      await pool.query(
        `INSERT INTO brain_facts
           (workspace_id, subject, predicate, object, source_episode_id, provenance,
            visible_to, status, predicate_cardinality,
            subject_key, predicate_key, object_key, object_cmp)
         VALUES ($1, 'business tier', 'priced at', '499 USD', $2,
                 '{"source":"warehouse"}'::jsonb, ARRAY['org'], 'published', 'multi',
                 'business tier', 'priced at', '499 usd', 'money:USD:499')`,
        [ws, ep],
      );
      const draft = await seedFact(
        ws,
        ep,
        { subject: "business tier", predicate: "priced at", object: "599 USD" },
        { status: "draft", rowCardinality: "multi" },
      );

      const { rows } = await pool.query<{ held_back: number }>(CARDINALITY_HELD_BACK_COUNT_SQL, [
        ws,
        [draft],
      ]);
      expect(
        rows[0]!.held_back,
        "the uncurated count reported a pair the TIER guard blocks permanently — curating the predicate would NOT make it supersede, so the number is a false promise",
      ).toBe(0);
    },
    PG_TEST_TIMEOUT_MS,
  );

  // -------------------------------------------------------------------------
  // The key is the CANONICAL predicate
  // -------------------------------------------------------------------------

  it(
    "one entry serves every spelling the vocabulary merges into the canonical predicate",
    async () => {
      // The reason the table is keyed on `predicate_key` — `alias(lexicalNorm(…))`
      // — rather than on a raw norm. `Priced At` and `priced at` are one slot,
      // so one curation decision covers both; keying on the surface would hold
      // two entries for one slot and put the disagreement straight back.
      const ws = "ws-5027-canonical-key";
      const ep = await seedEpisode(ws, "canonical");
      await seedFact(
        ws,
        ep,
        { subject: "Business Tier", predicate: "Priced At", object: "499 USD" },
        { status: "published", rowCardinality: "multi" },
      );
      await seedFact(
        ws,
        ep,
        { subject: "business tier", predicate: "priced at", object: "599 USD" },
        { status: "draft", rowCardinality: "multi" },
      );
      await curate(ws, "priced at", "single");

      expect(await collisionCount(ws)).toBe(1);
    },
    PG_TEST_TIMEOUT_MS,
  );

  it(
    "a fact whose predicate norms away never supersedes — a NULL key matches no entry",
    async () => {
      // `identityKey` answers NULL for a surface made only of separators, which
      // is permanent and legal. Such a row must fail CLOSED: it can match no
      // entry, so it can never be licensed to retire a belief. The CHECK on the
      // table is the other half — an entry keyed `''` would describe every
      // degenerate predicate in the workspace at once.
      const ws = "ws-5027-degenerate";
      await expect(
        pool.query(
          `INSERT INTO brain_predicate_cardinality
             (workspace_id, predicate_key, cardinality, status, source_class, proposed_by)
           VALUES ($1, '', 'single', 'approved', 'human', 'curator-1')`,
          [ws],
        ),
      ).rejects.toThrow(/ck_brain_predicate_cardinality_key_present/);

      const declared = await declarePredicateCardinality(pool, ws, {
        predicateKey: slotKey("---", identityVocabulary.predicate),
        cardinality: "single",
        authoredBy: "curator-1",
      });
      expect(declared).toMatchObject({ ok: false, refusal: "degenerate-key" });
    },
    PG_TEST_TIMEOUT_MS,
  );

  // ── the SURFACE-addressed decide seam (#5088) ──────────────────────────
  //
  // ⚠️ This entry point had NO test. It is referenced by the queue's decide
  // route — which mocks it — and by nothing else, so its own docstring named a
  // risk nothing measured: *"deciding `is priced at` once `is priced at → priced
  // at` is approved must land on `priced at`. An identity default would address
  // a row that does not exist and report `false`"* — i.e. a pending proposal
  // silently reported to the approver as a lost race.

  it(
    "⚠️ applies the workspace's ALIAS CLOSURE, so a decide lands on the slot the claims occupy",
    async () => {
      const ws = `ws-decide-surface-${Date.now()}`;
      await proposePredicateCardinality(pool, ws, {
        predicateKey: "priced at",
        cardinality: "single",
        sourceClass: "correction_event",
        proposedBy: CORRECTION_EVENT_PRODUCER,
      });

      // The approver names the spelling they SEE; the closure maps it onto the
      // canonical key the proposal is stored under. An identity default would
      // address `is priced at`, match no row, and report "nothing to decide".
      const decided = await decidePredicateCardinalityForSurface(pool, ws, {
        predicateSurface: "Is Priced At",
        verdict: "approved",
        reviewedBy: "user-owner",
        predicateAlias: (norm) => (norm === "is priced at" ? "priced at" : norm),
        requestId: "req-decide",
      });
      expect(decided).toBe("decided");
      expect(await readPredicateCardinality(pool, ws, "priced at")).toMatchObject({
        cardinality: "single",
        status: "approved",
      });
      // `reviewedBy` is not on `PredicateCardinalityRecord` (the read model
      // carries no reviewer), so the audit column is checked directly — it is
      // the first thing an audit of a retroactive re-key reads.
      const { rows } = await pool.query<{ reviewed_by: string | null }>(
        `SELECT reviewed_by FROM brain_predicate_cardinality
          WHERE workspace_id = $1 AND predicate_key = 'priced at'`,
        [ws],
      );
      expect(rows[0]!.reviewed_by).toBe("user-owner");
    },
    PG_TEST_TIMEOUT_MS,
  );

  it(
    "⚠️ a REJECTION is stored as a rejection, never as the approval",
    async () => {
      // Every other decide test on this seam passes `verdict: "approved"` — so
      // the verdict was, in effect, a constant, and the route half had the same
      // hole (a rejection answering the approved arm left the whole route suite green). The
      // consequence of getting it backwards is the maximal one available on this
      // surface: `single` + `approved` arms retroactive supersession for every
      // published pair in the slot at the next publish.
      const ws = `ws-decide-reject-${Date.now()}`;
      await proposePredicateCardinality(pool, ws, {
        predicateKey: "reports to",
        cardinality: "single",
        sourceClass: "correction_event",
        proposedBy: CORRECTION_EVENT_PRODUCER,
      });
      const decided = await decidePredicateCardinalityForSurface(pool, ws, {
        predicateSurface: "Reports To",
        verdict: "rejected",
        reviewedBy: "user-owner",
        predicateAlias: identityAlias,
        requestId: "req-reject",
      });
      expect(decided).toBe("decided");
      const record = await readPredicateCardinality(pool, ws, "reports to");
      expect(record).toMatchObject({ status: "rejected" });
      // ⚠️ And the GATE is not armed. `cardinalitySingleSql` requires
      // `status = 'approved'`, so this is the assertion that would catch a
      // verdict silently defaulted to approved even if the column read back
      // correctly for some other reason.
      const { rows } = await pool.query<{ armed: boolean }>(
        `SELECT EXISTS (
           SELECT 1 FROM brain_predicate_cardinality c
            WHERE c.workspace_id = $1 AND c.predicate_key = 'reports to'
              AND c.cardinality = 'single' AND c.status = 'approved') AS armed`,
        [ws],
      );
      expect(rows[0]!.armed).toBe(false);
    },
    PG_TEST_TIMEOUT_MS,
  );

  it(
    "POSITIVE CONTROL — without the closure the same surface addresses NOTHING",
    async () => {
      // Without this the test above passes with `predicateAlias` ignored, since
      // `slotKey` under the identity lookup would still key *some* row if the
      // fixture happened to be stored under the un-aliased norm.
      const ws = `ws-decide-noalias-${Date.now()}`;
      await proposePredicateCardinality(pool, ws, {
        predicateKey: "priced at",
        cardinality: "single",
        sourceClass: "correction_event",
        proposedBy: CORRECTION_EVENT_PRODUCER,
      });
      const decided = await decidePredicateCardinalityForSurface(pool, ws, {
        predicateSurface: "Is Priced At",
        verdict: "approved",
        reviewedBy: "user-owner",
        predicateAlias: identityAlias,
      });
      expect(decided).toBe("not-pending");
      expect(await readPredicateCardinality(pool, ws, "priced at")).toMatchObject({
        status: "pending",
      });
    },
    PG_TEST_TIMEOUT_MS,
  );

  it(
    "⚠️ distinguishes UNADDRESSABLE from a lost race — they render as opposite sentences",
    async () => {
      // A bare boolean collapsed the two, the route mapped both to
      // `nothing_to_decide`, and the client said *"someone else got there
      // first"* — a confident, specific, WRONG explanation for a request that
      // never addressed a row at all.
      const ws = `ws-decide-degenerate-${Date.now()}`;
      const unaddressable = await decidePredicateCardinalityForSurface(pool, ws, {
        predicateSurface: "---",
        verdict: "approved",
        reviewedBy: "user-owner",
        predicateAlias: identityAlias,
      });
      expect(unaddressable).toBe("unaddressable");

      // ...and a REAL row decided twice is `not-pending` the second time, which
      // is the race the first sentence must not be confused with.
      await proposePredicateCardinality(pool, ws, {
        predicateKey: "reports to",
        cardinality: "single",
        sourceClass: "correction_event",
        proposedBy: CORRECTION_EVENT_PRODUCER,
      });
      const input = {
        predicateSurface: "reports to",
        verdict: "approved" as const,
        reviewedBy: "user-owner",
        predicateAlias: identityAlias,
      };
      expect(await decidePredicateCardinalityForSurface(pool, ws, input)).toBe("decided");
      expect(await decidePredicateCardinalityForSurface(pool, ws, input)).toBe("not-pending");
    },
    PG_TEST_TIMEOUT_MS,
  );
});
