#!/usr/bin/env bash
# Vendor `packages/oauth-helper/src/` into `plugins/mcp/src/_oauth-helper/`
# so the CLI loopback flow can import the shared OAuth 2.1 + DCR + PKCE
# primitives via a relative path that resolves at runtime in the
# published `@useatlas/mcp` package.
#
# Why vendor: the canonical helper lives at `@atlas/oauth-helper` which
# is internal-only (not published to npm). `@useatlas/mcp` ships raw
# TypeScript and runs via `bunx`, so a `@atlas/oauth-helper` import
# would fail to resolve when an end-user installs the package.
# Vendoring + relative imports keeps the helper internal-only while
# letting the published CLI find the source.
#
# Runs from:
#   - `bun install` (via the package's `prepare` script)
#   - `npm publish` (via `prepare`, before pack)
#   - the drift check at `scripts/check-oauth-helper-drift.sh`
#
# The destination is gitignored — the canonical source is in
# `packages/oauth-helper/src/`. Edits should always go to the canonical
# location; this script overwrites the vendored copy on every run AND
# stamps each `.ts` file with an AUTO-GENERATED header so an editor
# opened on a vendored file shows the warning before the user types.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PLUGIN_ROOT/../.." && pwd)"

SRC="$REPO_ROOT/packages/oauth-helper/src"
DEST="$PLUGIN_ROOT/src/_oauth-helper"

if [ ! -d "$SRC" ]; then
  echo "vendor-oauth-helper: source missing at $SRC" >&2
  echo "vendor-oauth-helper: run \`bun install\` from the repo root first" >&2
  exit 1
fi

rm -rf "$DEST"
mkdir -p "$DEST"

# Copy every .ts under src/ preserving the subdirectory layout so
# internal modules (`_internal/http.ts`, `_internal/encoding.ts`) keep
# their relative-import shape. Each file is prefixed with an
# AUTO-GENERATED header so a contributor opening the vendored copy
# directly sees the warning at the top of their editor pane.
HEADER='// AUTO-GENERATED — DO NOT EDIT.\n// Canonical source: packages/oauth-helper/src/\n// Regenerated by plugins/mcp/scripts/vendor-oauth-helper.sh on every\n// `bun install` and `npm publish`. Edits made here are overwritten.\n'

count=0
while IFS= read -r -d '' rel; do
  rel_path="${rel#./}"
  target="$DEST/$rel_path"
  mkdir -p "$(dirname "$target")"
  {
    printf '%b' "$HEADER"
    cat "$SRC/$rel_path"
  } > "$target"
  count=$((count + 1))
done < <(cd "$SRC" && find . -type f -name "*.ts" -print0)

# Post-copy invariant — every file the CLI imports must be present.
# A partial copy (e.g. `find` losing entries mid-stream, a future
# refactor renaming a primitive without updating this list) would
# otherwise leave the vendored tree looking superficially populated
# but missing files the CLI's static imports need at runtime.
required=(
  "index.ts"
  "errors.ts"
  "brands.ts"
  "discover.ts"
  "register.ts"
  "exchange.ts"
  "jwt.ts"
  "validate.ts"
  "pkce.ts"
  "authorize-url.ts"
  "_internal/http.ts"
  "_internal/encoding.ts"
)
for f in "${required[@]}"; do
  if [ ! -f "$DEST/$f" ]; then
    echo "vendor-oauth-helper: missing $f after copy — aborting" >&2
    echo "vendor-oauth-helper: $count file(s) copied; required entry missing" >&2
    exit 1
  fi
done

# Drop a sibling README so a contributor browsing the directory tree
# (rather than opening a single .ts file) also sees the warning.
cat > "$DEST/README.md" <<'EOF'
# Vendored `@atlas/oauth-helper`

**This directory is auto-generated. Do not edit.**

The canonical source lives at `packages/oauth-helper/src/`. This copy
exists so `@useatlas/mcp`'s published TS bundle (which ships source raw,
not a build artifact) can resolve the OAuth 2.1 + DCR + PKCE primitives
without a runtime dependency on `@atlas/oauth-helper` (internal-only).

The contents are regenerated by `scripts/vendor-oauth-helper.sh` on
every `bun install` and `npm publish`. To change anything here, edit
the canonical source and rerun the script (it runs automatically on
`bun install`).

CI runs `scripts/check-oauth-helper-drift.sh` to fail loudly if a
contributor edits the vendored copy directly without re-running the
vendor script — the canonical source is the only legitimate edit point.

See `packages/oauth-helper/README.md` for the helper's public surface.
EOF
