#!/usr/bin/env bash
# Vendor `packages/oauth-helper/src/` into `plugins/mcp/src/_oauth-helper/`
# so the CLI loopback flow can import the shared OAuth 2.1 + DCR + PKCE
# primitives via a relative path that resolves at runtime in the
# published `@useatlas/mcp` package.
#
# Why vendor: the canonical helper lives at `@atlas/oauth-helper` which
# is internal-only (not published to npm) — see #2203. `@useatlas/mcp`
# ships raw TypeScript and runs via `bunx`, so a `@atlas/oauth-helper`
# import would fail to resolve when an end-user installs the package.
# Vendoring + relative imports keeps the helper internal-only while
# letting the published CLI find the source.
#
# Runs from:
#   - `bun install` (via the package's `prepare` script)
#   - `npm publish` (via `prepare`, before pack)
#   - CI's drift check below if the vendored copy diverges
#
# The destination is gitignored — the canonical source is in
# `packages/oauth-helper/src/`. Edits should always go to the canonical
# location; this script overwrites the vendored copy on every run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PLUGIN_ROOT/../.." && pwd)"

SRC="$REPO_ROOT/packages/oauth-helper/src"
DEST="$PLUGIN_ROOT/src/_oauth-helper"

if [ ! -d "$SRC" ]; then
  echo "vendor-oauth-helper: source missing at $SRC" >&2
  echo "vendor-oauth-helper: run \`bun install\` from the repo root first" >&2
  exit 1
fi

rm -rf "$DEST"
mkdir -p "$DEST"

# Copy every .ts under src/ preserving the subdirectory layout so
# internal modules (`_internal/http.ts`, `_internal/encoding.ts`) keep
# their relative-import shape.
(cd "$SRC" && find . -type f -name "*.ts" -print0) | while IFS= read -r -d '' rel; do
  rel_path="${rel#./}"
  target="$DEST/$rel_path"
  mkdir -p "$(dirname "$target")"
  cp "$SRC/$rel_path" "$target"
done

# Drop a header marker so a future contributor opening one of these
# files knows it's a generated mirror, not the canonical source.
cat > "$DEST/README.md" <<'EOF'
# Vendored `@atlas/oauth-helper`

**This directory is auto-generated. Do not edit.**

The canonical source lives at `packages/oauth-helper/src/`. This copy
exists so `@useatlas/mcp`'s published TS bundle (which ships source raw,
not a build artifact) can resolve the OAuth 2.1 + DCR + PKCE primitives
without a runtime dependency on `@atlas/oauth-helper` (internal-only).

The contents are regenerated by `scripts/vendor-oauth-helper.sh` on
every `bun install` and `npm publish`. To change anything here, edit
the canonical source and rerun the script (it runs automatically on
`bun install`).

See `packages/oauth-helper/README.md` for the helper's public surface.
EOF
