/**
 * Smoke tests for the OAuth/MCP `.well-known` metadata routes (#2024 PR C).
 * The `/security.txt` suite (#4467) is documented at its describe block
 * below — unlike the metadata routes, it is auth-mode-independent.
 *
 * The actual content of the metadata documents is generated by Better
 * Auth's `oauthProvider` plugin; we don't re-test that. What we DO pin:
 *   • the routes exist at the canonical paths
 *   • they return 404 in non-managed-auth mode (no leak about the
 *     plugin's existence)
 *   • CORS is permissive (MCP Inspector + browser MCP clients need it)
 *   • the protected-resource endpoint reads the workspace_id path param
 */

import {
  describe,
  it,
  expect,
  beforeEach,
  afterAll,
  mock,
} from "bun:test";
import { readFileSync } from "node:fs";

// ── Mocks ──────────────────────────────────────────────────────────

const mockDetectAuthMode: { current: "managed" | "none" } = { current: "managed" };

void mock.module("@atlas/api/lib/auth/detect", () => ({
  detectAuthMode: () => mockDetectAuthMode.current,
}));

// Resolved deploy mode read by the /.well-known/security.txt gate (#4467).
// Driven through the real config module via `_setConfigForTest` (the
// health.test.ts pattern) rather than a partial `mock.module` — the real
// `getConfig()` null path is what the fail-closed test exercises.
const { _setConfigForTest } = await import("@atlas/api/lib/config");

function setDeployModeForTest(mode: "saas" | "self-hosted" | undefined) {
  if (mode === undefined) {
    _setConfigForTest(null);
    return;
  }
  // oxlint-disable-next-line @typescript-eslint/no-explicit-any -- partial ResolvedConfig is sufficient for the deployMode path
  _setConfigForTest({ deployMode: mode } as any);
}

// Well-known.ts dynamically imports the auth instance + the
// oauth-provider helpers. We stub both with handlers that return a
// well-shaped response so the route's wiring can be exercised without
// standing up Better Auth.
void mock.module("@atlas/api/lib/auth/server", () => ({
  getAuthInstance: () => ({
    api: {
      // Helpers in @better-auth/oauth-provider read these — stubs are
      // sufficient because the helper functions themselves are mocked
      // below.
      getOAuthServerConfig: () => ({}),
      getOpenIdConfig: () => ({}),
    },
  }),
}));

void mock.module("@better-auth/oauth-provider", () => ({
  oauthProviderAuthServerMetadata: () =>
    () =>
      new Response(
        JSON.stringify({
          issuer: "https://example.test/api/auth",
          token_endpoint: "https://example.test/api/auth/oauth2/token",
          authorization_endpoint:
            "https://example.test/api/auth/oauth2/authorize",
        }),
        { status: 200, headers: { "Content-Type": "application/json" } },
      ),
  oauthProviderOpenIdConfigMetadata: () =>
    () =>
      new Response(
        JSON.stringify({
          issuer: "https://example.test/api/auth",
          authorization_endpoint:
            "https://example.test/api/auth/oauth2/authorize",
          jwks_uri: "https://example.test/api/auth/jwks",
        }),
        { status: 200, headers: { "Content-Type": "application/json" } },
      ),
}));

void mock.module("@better-auth/oauth-provider/resource-client", () => ({
  oauthProviderResourceClient: () => ({
    getActions: () => ({
      getProtectedResourceMetadata: async (overrides: {
        resource?: string;
        authorization_servers?: string[];
        bearer_methods_supported?: string[];
        scopes_supported?: string[];
      }) => ({
        resource: overrides.resource ?? "",
        authorization_servers: overrides.authorization_servers ?? [],
        bearer_methods_supported: overrides.bearer_methods_supported ?? [],
        scopes_supported: overrides.scopes_supported ?? [],
      }),
    }),
  }),
}));

// ── Import routes after mocks ──────────────────────────────────────

const { wellKnown } = await import("../routes/well-known");
const { Hono } = await import("hono");

afterAll(() => {
  _setConfigForTest(null);
  mock.restore();
});

beforeEach(() => {
  mockDetectAuthMode.current = "managed";
  setDeployModeForTest("self-hosted");
});

async function startServer() {
  const app = new Hono();
  app.route("/.well-known", wellKnown);
  const server = Bun.serve({ port: 0, idleTimeout: 0, fetch: app.fetch });
  return {
    url: `http://localhost:${server.port}`,
    close: () => server.stop(true),
  };
}

describe("well-known — managed auth mode", () => {
  it("serves /.well-known/oauth-authorization-server/api/auth", async () => {
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-authorization-server/api/auth`,
      );
      expect(res.status).toBe(200);
      expect(res.headers.get("access-control-allow-origin")).toBe("*");
      const body = (await res.json()) as { issuer: string };
      expect(body.issuer).toBe("https://example.test/api/auth");
    } finally {
      await handle.close();
    }
  });

  it("serves /.well-known/openid-configuration/api/auth", async () => {
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/openid-configuration/api/auth`,
      );
      expect(res.status).toBe(200);
      expect(res.headers.get("access-control-allow-origin")).toBe("*");
      const body = (await res.json()) as { jwks_uri: string };
      expect(body.jwks_uri).toBe("https://example.test/api/auth/jwks");
    } finally {
      await handle.close();
    }
  });

  it("serves /.well-known/oauth-protected-resource/mcp/:workspace_id with the region-scoped resource URI", async () => {
    // The metadata is fetched per-workspace path so future per-workspace
    // extensions have somewhere to live, but the `resource` audience in
    // the document is region-scoped (`<base>/mcp`, no workspace
    // segment). Workspace isolation runs through the JWT claim, not the
    // audience — see well-known.ts buildResourceUri docstring.
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-protected-resource/mcp/org_xyz`,
      );
      expect(res.status).toBe(200);
      const body = (await res.json()) as {
        resource: string;
        scopes_supported: string[];
        bearer_methods_supported: string[];
      };
      // Region-scoped resource. Must NOT carry the workspace id —
      // otherwise the audience advertised here won't match what
      // `resolveOAuthValidAudiences` accepts on the issuer side, and
      // every RFC-8707 token request 401s in production.
      expect(body.resource).toMatch(/\/mcp$/);
      expect(body.resource).not.toContain("/mcp/org_xyz");
      expect(body.scopes_supported).toEqual(["mcp:read", "mcp:write"]);
      expect(body.bearer_methods_supported).toEqual(["header"]);
    } finally {
      await handle.close();
    }
  });

  it("advertises mcp.useatlas.dev as the resource when ATLAS_PUBLIC_API_URL points at the us-region api host", async () => {
    // #2068 — mcp.useatlas.dev is the canonical hostname for the
    // hosted MCP endpoint. The protected-resource metadata must
    // advertise the brand hostname so a standards-compliant MCP client
    // reading this doc binds its token request to the
    // `https://mcp.useatlas.dev/mcp` audience and never sees the
    // underlying regional `api.*` infra. The audience the issuer
    // accepts (`resolveOAuthValidAudiences`) keeps the regional fallback
    // for backward compat — this doc just stops naming it.
    const prev = process.env.ATLAS_PUBLIC_API_URL;
    process.env.ATLAS_PUBLIC_API_URL = "https://api.useatlas.dev";
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-protected-resource/mcp/org_xyz`,
      );
      expect(res.status).toBe(200);
      const body = (await res.json()) as { resource: string };
      expect(body.resource).toBe("https://mcp.useatlas.dev/mcp");
    } finally {
      await handle.close();
      if (prev === undefined) delete process.env.ATLAS_PUBLIC_API_URL;
      else process.env.ATLAS_PUBLIC_API_URL = prev;
    }
  });

  it("advertises mcp-eu.useatlas.dev for the eu-region api host", async () => {
    const prev = process.env.ATLAS_PUBLIC_API_URL;
    process.env.ATLAS_PUBLIC_API_URL = "https://api-eu.useatlas.dev";
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-protected-resource/mcp/org_xyz`,
      );
      const body = (await res.json()) as { resource: string };
      expect(body.resource).toBe("https://mcp-eu.useatlas.dev/mcp");
    } finally {
      await handle.close();
      if (prev === undefined) delete process.env.ATLAS_PUBLIC_API_URL;
      else process.env.ATLAS_PUBLIC_API_URL = prev;
    }
  });

  it("advertises mcp.useatlas.dev verbatim when ATLAS_PUBLIC_API_URL already is the brand host (operator post-cutover flip)", async () => {
    // The asymmetric `brandedMcpHost` returns null for brand inputs;
    // the caller falls back to the trimmed base. Pin that branch so a
    // future regex relaxation that accidentally matched
    // `mcp.useatlas.dev` and tried to "flip" it (rendering
    // `https://api.useatlas.dev/mcp`) silently undoes the cutover —
    // this test catches that.
    const prev = process.env.ATLAS_PUBLIC_API_URL;
    process.env.ATLAS_PUBLIC_API_URL = "https://mcp.useatlas.dev";
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-protected-resource/mcp/org_xyz`,
      );
      const body = (await res.json()) as { resource: string };
      expect(body.resource).toBe("https://mcp.useatlas.dev/mcp");
    } finally {
      await handle.close();
      if (prev === undefined) delete process.env.ATLAS_PUBLIC_API_URL;
      else process.env.ATLAS_PUBLIC_API_URL = prev;
    }
  });

  it("keeps the api.* hostname for non-useatlas.dev bases (self-hosted unchanged)", async () => {
    const prev = process.env.ATLAS_PUBLIC_API_URL;
    process.env.ATLAS_PUBLIC_API_URL = "https://api.example.test";
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-protected-resource/mcp/org_xyz`,
      );
      const body = (await res.json()) as { resource: string };
      expect(body.resource).toBe("https://api.example.test/mcp");
    } finally {
      await handle.close();
      if (prev === undefined) delete process.env.ATLAS_PUBLIC_API_URL;
      else process.env.ATLAS_PUBLIC_API_URL = prev;
    }
  });

  it("answers OPTIONS preflight with CORS-permissive 204", async () => {
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-authorization-server/api/auth`,
        { method: "OPTIONS" },
      );
      expect(res.status).toBe(204);
      expect(res.headers.get("access-control-allow-origin")).toBe("*");
      expect(res.headers.get("access-control-allow-methods")).toContain("GET");
    } finally {
      await handle.close();
    }
  });
});

describe("well-known — non-managed auth mode", () => {
  it("returns 404 for every metadata route when auth is not managed", async () => {
    mockDetectAuthMode.current = "none";
    const handle = await startServer();
    try {
      for (const path of [
        "/.well-known/oauth-authorization-server/api/auth",
        "/.well-known/openid-configuration/api/auth",
        "/.well-known/oauth-protected-resource/mcp/org_anything",
      ]) {
        const res = await fetch(`${handle.url}${path}`);
        expect(res.status).toBe(404);
        const body = (await res.json()) as { error: string };
        expect(body.error).toBe("not_found");
      }
    } finally {
      await handle.close();
    }
  });
});

describe("well-known — helpers fail to load", () => {
  // The earlier wiring collapsed import-failure into the not-managed
  // 404 path, hiding boot bugs (missing @better-auth/oauth-provider,
  // crashed getAuthInstance) behind a cheerful "managed auth not
  // enabled" message. Now distinguished via the tagged outcome — this
  // test pins the 503 path so a future refactor can't silently
  // re-collapse them.
  it("returns 503 with a requestId when getAuthInstance throws", async () => {
    mockDetectAuthMode.current = "managed";
    // Swap the auth-server module to throw on getAuthInstance(). We
    // restore the success shape in the `finally` so subsequent tests
    // in this file (if any are added below) see the original mock.
    // `bun:test` `mock.module` doesn't return a `.restore()` handle,
    // so we explicitly re-install the success shape to revert.
    void mock.module("@atlas/api/lib/auth/server", () => ({
      getAuthInstance: () => {
        throw new Error("better-auth boot failure");
      },
    }));
    try {
      const handle = await startServer();
      try {
        const res = await fetch(
          `${handle.url}/.well-known/oauth-authorization-server/api/auth`,
        );
        expect(res.status).toBe(503);
        const body = (await res.json()) as {
          error: string;
          requestId?: string;
          reason?: string;
        };
        expect(body.error).toBe("metadata_unavailable");
        expect(body.requestId).toBeTruthy();
        // Surface the underlying reason so a customer escalation can
        // map response → log line directly.
        expect(body.reason).toContain("better-auth boot failure");
      } finally {
        await handle.close();
      }
    } finally {
      void mock.module("@atlas/api/lib/auth/server", () => ({
        getAuthInstance: () => ({
          api: {
            getOAuthServerConfig: () => ({}),
            getOpenIdConfig: () => ({}),
          },
        }),
      }));
    }
  });
});

describe("well-known — /.well-known/security.txt (#4467)", () => {
  // RFC 9116 is per-origin: the api/mcp origins must answer
  // /.well-known/security.txt themselves. On SaaS they redirect to the
  // canonical www copy (the SSOT — RFC 9116 §3 permits redirects) instead
  // of serving a second file that could drift.
  it("302-redirects to the canonical www copy on SaaS deploys", async () => {
    setDeployModeForTest("saas");
    const handle = await startServer();
    try {
      const res = await fetch(`${handle.url}/.well-known/security.txt`, {
        redirect: "manual",
      });
      expect(res.status).toBe(302);
      expect(res.headers.get("location")).toBe(
        "https://www.useatlas.dev/.well-known/security.txt",
      );
      // ...and the literal above must BE the SSOT's own Canonical URL, so a
      // move of the canonical policy location fails here and forces the
      // route to move with it (same drift lock as the docs-origin test in
      // apps/docs/src/lib/__tests__/security-txt-redirect.test.ts).
      expect(res.headers.get("location")).toBe(readWwwCanonicalUrl());
      // Crawler-friendly cache pinned — a refactor that drops the header
      // (or fat-fingers the TTL) should not pass silently.
      expect(res.headers.get("cache-control")).toBe("public, max-age=3600");
    } finally {
      await handle.close();
    }
  });

  it("does not depend on the auth mode (a researcher probes unauthenticated)", async () => {
    setDeployModeForTest("saas");
    mockDetectAuthMode.current = "none";
    const handle = await startServer();
    try {
      const res = await fetch(`${handle.url}/.well-known/security.txt`, {
        redirect: "manual",
      });
      expect(res.status).toBe(302);
    } finally {
      await handle.close();
    }
  });

  it("404s on self-hosted deploys (Atlas's security contact is not the operator's)", async () => {
    setDeployModeForTest("self-hosted");
    const handle = await startServer();
    try {
      const res = await fetch(`${handle.url}/.well-known/security.txt`);
      expect(res.status).toBe(404);
      const body = (await res.json()) as { error: string };
      expect(body.error).toBe("not_found");
    } finally {
      await handle.close();
    }
  });

  it("404s when no config resolved (fails closed to self-hosted behavior)", async () => {
    setDeployModeForTest(undefined);
    const handle = await startServer();
    try {
      const res = await fetch(`${handle.url}/.well-known/security.txt`);
      expect(res.status).toBe(404);
    } finally {
      await handle.close();
    }
  });
});

/**
 * Read the `Canonical:` URL out of the www SSOT copy
 * (apps/www/public/.well-known/security.txt) so the redirect target the API
 * advertises is pinned to the file it points at, not to a second literal.
 */
function readWwwCanonicalUrl(): string {
  // packages/api/src/api/__tests__ -> repo root
  const ssotPath = new URL(
    "../../../../../apps/www/public/.well-known/security.txt",
    import.meta.url,
  );
  const body = readFileSync(ssotPath, "utf8");
  const match = body.match(/^Canonical:\s*(\S+)\s*$/m);
  if (!match) {
    throw new Error(
      "No Canonical field in apps/www/public/.well-known/security.txt — cannot derive the expected redirect target",
    );
  }
  return match[1];
}
