/**
 * Smoke tests for the .well-known metadata routes (#2024 PR C).
 *
 * The actual content of the documents is generated by Better Auth's
 * `oauthProvider` plugin; we don't re-test that. What we DO pin:
 *   • the routes exist at the canonical paths
 *   • they return 404 in non-managed-auth mode (no leak about the
 *     plugin's existence)
 *   • CORS is permissive (MCP Inspector + browser MCP clients need it)
 *   • the protected-resource endpoint reads the workspace_id path param
 */

import {
  describe,
  it,
  expect,
  beforeEach,
  afterAll,
  mock,
} from "bun:test";

// ── Mocks ──────────────────────────────────────────────────────────

const mockDetectAuthMode: { current: "managed" | "none" } = { current: "managed" };

mock.module("@atlas/api/lib/auth/detect", () => ({
  detectAuthMode: () => mockDetectAuthMode.current,
}));

// Well-known.ts dynamically imports the auth instance + the
// oauth-provider helpers. We stub both with handlers that return a
// well-shaped response so the route's wiring can be exercised without
// standing up Better Auth.
mock.module("@atlas/api/lib/auth/server", () => ({
  getAuthInstance: () => ({
    api: {
      // Helpers in @better-auth/oauth-provider read these — stubs are
      // sufficient because the helper functions themselves are mocked
      // below.
      getOAuthServerConfig: () => ({}),
      getOpenIdConfig: () => ({}),
    },
  }),
}));

mock.module("@better-auth/oauth-provider", () => ({
  oauthProviderAuthServerMetadata: () =>
    () =>
      new Response(
        JSON.stringify({
          issuer: "https://example.test/api/auth",
          token_endpoint: "https://example.test/api/auth/oauth2/token",
          authorization_endpoint:
            "https://example.test/api/auth/oauth2/authorize",
        }),
        { status: 200, headers: { "Content-Type": "application/json" } },
      ),
  oauthProviderOpenIdConfigMetadata: () =>
    () =>
      new Response(
        JSON.stringify({
          issuer: "https://example.test/api/auth",
          authorization_endpoint:
            "https://example.test/api/auth/oauth2/authorize",
          jwks_uri: "https://example.test/api/auth/jwks",
        }),
        { status: 200, headers: { "Content-Type": "application/json" } },
      ),
}));

mock.module("@better-auth/oauth-provider/resource-client", () => ({
  oauthProviderResourceClient: () => ({
    getActions: () => ({
      getProtectedResourceMetadata: async (overrides: {
        resource?: string;
        authorization_servers?: string[];
        bearer_methods_supported?: string[];
        scopes_supported?: string[];
      }) => ({
        resource: overrides.resource ?? "",
        authorization_servers: overrides.authorization_servers ?? [],
        bearer_methods_supported: overrides.bearer_methods_supported ?? [],
        scopes_supported: overrides.scopes_supported ?? [],
      }),
    }),
  }),
}));

// ── Import routes after mocks ──────────────────────────────────────

const { wellKnown } = await import("../routes/well-known");
const { Hono } = await import("hono");

afterAll(() => {
  mock.restore();
});

beforeEach(() => {
  mockDetectAuthMode.current = "managed";
});

async function startServer() {
  const app = new Hono();
  app.route("/.well-known", wellKnown);
  const server = Bun.serve({ port: 0, idleTimeout: 0, fetch: app.fetch });
  return {
    url: `http://localhost:${server.port}`,
    close: () => server.stop(true),
  };
}

describe("well-known — managed auth mode", () => {
  it("serves /.well-known/oauth-authorization-server/api/auth", async () => {
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-authorization-server/api/auth`,
      );
      expect(res.status).toBe(200);
      expect(res.headers.get("access-control-allow-origin")).toBe("*");
      const body = (await res.json()) as { issuer: string };
      expect(body.issuer).toBe("https://example.test/api/auth");
    } finally {
      handle.close();
    }
  });

  it("serves /.well-known/openid-configuration/api/auth", async () => {
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/openid-configuration/api/auth`,
      );
      expect(res.status).toBe(200);
      expect(res.headers.get("access-control-allow-origin")).toBe("*");
      const body = (await res.json()) as { jwks_uri: string };
      expect(body.jwks_uri).toBe("https://example.test/api/auth/jwks");
    } finally {
      handle.close();
    }
  });

  it("serves /.well-known/oauth-protected-resource/mcp/:workspace_id with the region-scoped resource URI", async () => {
    // The metadata is fetched per-workspace path so future per-workspace
    // extensions have somewhere to live, but the `resource` audience in
    // the document is region-scoped (`<base>/mcp`, no workspace
    // segment). Workspace isolation runs through the JWT claim, not the
    // audience — see well-known.ts buildResourceUri docstring.
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-protected-resource/mcp/org_xyz`,
      );
      expect(res.status).toBe(200);
      const body = (await res.json()) as {
        resource: string;
        scopes_supported: string[];
        bearer_methods_supported: string[];
      };
      // Region-scoped resource. Must NOT carry the workspace id —
      // otherwise the audience advertised here won't match what
      // `resolveOAuthValidAudiences` accepts on the issuer side, and
      // every RFC-8707 token request 401s in production.
      expect(body.resource).toMatch(/\/mcp$/);
      expect(body.resource).not.toContain("/mcp/org_xyz");
      expect(body.scopes_supported).toEqual(["mcp:read", "mcp:write"]);
      expect(body.bearer_methods_supported).toEqual(["header"]);
    } finally {
      handle.close();
    }
  });

  it("answers OPTIONS preflight with CORS-permissive 204", async () => {
    const handle = await startServer();
    try {
      const res = await fetch(
        `${handle.url}/.well-known/oauth-authorization-server/api/auth`,
        { method: "OPTIONS" },
      );
      expect(res.status).toBe(204);
      expect(res.headers.get("access-control-allow-origin")).toBe("*");
      expect(res.headers.get("access-control-allow-methods")).toContain("GET");
    } finally {
      handle.close();
    }
  });
});

describe("well-known — non-managed auth mode", () => {
  it("returns 404 for every metadata route when auth is not managed", async () => {
    mockDetectAuthMode.current = "none";
    const handle = await startServer();
    try {
      for (const path of [
        "/.well-known/oauth-authorization-server/api/auth",
        "/.well-known/openid-configuration/api/auth",
        "/.well-known/oauth-protected-resource/mcp/org_anything",
      ]) {
        const res = await fetch(`${handle.url}${path}`);
        expect(res.status).toBe(404);
        const body = (await res.json()) as { error: string };
        expect(body.error).toBe("not_found");
      }
    } finally {
      handle.close();
    }
  });
});

describe("well-known — helpers fail to load", () => {
  // The earlier wiring collapsed import-failure into the not-managed
  // 404 path, hiding boot bugs (missing @better-auth/oauth-provider,
  // crashed getAuthInstance) behind a cheerful "managed auth not
  // enabled" message. Now distinguished via the tagged outcome — this
  // test pins the 503 path so a future refactor can't silently
  // re-collapse them.
  it("returns 503 with a requestId when getAuthInstance throws", async () => {
    mockDetectAuthMode.current = "managed";
    // Swap the auth-server module to throw on getAuthInstance(). We
    // restore the success shape in the `finally` so subsequent tests
    // in this file (if any are added below) see the original mock.
    // `bun:test` `mock.module` doesn't return a `.restore()` handle,
    // so we explicitly re-install the success shape to revert.
    mock.module("@atlas/api/lib/auth/server", () => ({
      getAuthInstance: () => {
        throw new Error("better-auth boot failure");
      },
    }));
    try {
      const handle = await startServer();
      try {
        const res = await fetch(
          `${handle.url}/.well-known/oauth-authorization-server/api/auth`,
        );
        expect(res.status).toBe(503);
        const body = (await res.json()) as {
          error: string;
          requestId?: string;
          reason?: string;
        };
        expect(body.error).toBe("metadata_unavailable");
        expect(body.requestId).toBeTruthy();
        // Surface the underlying reason so a customer escalation can
        // map response → log line directly.
        expect(body.reason).toContain("better-auth boot failure");
      } finally {
        handle.close();
      }
    } finally {
      mock.module("@atlas/api/lib/auth/server", () => ({
        getAuthInstance: () => ({
          api: {
            getOAuthServerConfig: () => ({}),
            getOpenIdConfig: () => ({}),
          },
        }),
      }));
    }
  });
});
