// @generated by scripts/generate-pricing-entitlements.ts — DO NOT EDIT.
//
// Mirror of the FeatureEntitlement SSOT
// (packages/api/src/lib/billing/feature-entitlement.ts) for the pricing
// comparison table. Regenerate with:
//
//   bun scripts/generate-pricing-entitlements.ts
//
// The drift guard scripts/check-pricing-parity.sh fails CI when this file
// is stale relative to FEATURE_ENTITLEMENTS, so the page's per-tier feature
// columns can never silently diverge from what the code actually enforces.
// The frontend (@atlas/www) imports only this plain data module and never
// @atlas/api — CLAUDE.md: the frontend is a pure HTTP client.

/** Marketing comparison-table columns, in display order. */
export type PricingColumn = "selfHosted" | "starter" | "pro" | "business";

/** Comparison-table section a gated feature renders under. */
export type EntitlementSection = "hosting" | "security & compliance";

/**
 * The entitlement sections in render order. Iterate this (rather than
 * hand-listing the section labels) so a new section added to the SSOT can't be
 * silently dropped from the page — every member is rendered or it's a visible
 * gap, not a quiet omission.
 */
export const ENTITLEMENT_SECTION_ORDER: readonly EntitlementSection[] = [
  "hosting", "security & compliance",
];

/** Stable wire id of a gated feature (matches the SSOT key). */
export type FeatureId = "residency" | "backups" | "white_label" | "sso" | "scim" | "custom_roles" | "ip_allowlist" | "approvals" | "audit_retention" | "masking" | "proactive";

/** One per-tier entitlement row mirrored from the SSOT. */
export interface EntitlementRow {
  /** Stable wire id of the gated feature (matches the SSOT key). */
  readonly feature: FeatureId;
  /** Row label shown verbatim in the comparison table. */
  readonly label: string;
  /** Section the row renders under. */
  readonly section: EntitlementSection;
  /** Whether each marketing tier unlocks the feature (true) or not (false). */
  readonly cells: Readonly<Record<PricingColumn, boolean>>;
}

/**
 * Per-tier feature entitlements, generated from FEATURE_ENTITLEMENTS. Each
 * cell is `isPlanEligible(columnTier, requiredTier)` — the same predicate
 * enforcement reads — so a cell is true iff that tier actually unlocks the
 * feature in code.
 */
export const ENTITLEMENT_ROWS: readonly EntitlementRow[] = [
  {
    feature: "residency",
    label: "Data residency",
    section: "hosting",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "backups",
    label: "Automated backups",
    section: "hosting",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "white_label",
    label: "White-label branding",
    section: "hosting",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "sso",
    label: "SSO (SAML + OIDC)",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "scim",
    label: "SCIM directory sync",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "custom_roles",
    label: "Custom roles & permissions",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "ip_allowlist",
    label: "IP allowlisting",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "approvals",
    label: "Approval workflows",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "audit_retention",
    label: "Audit log retention policies",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "masking",
    label: "PII detection & masking",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
  {
    feature: "proactive",
    label: "Proactive monitoring",
    section: "security & compliance",
    cells: { selfHosted: false, starter: false, pro: false, business: true },
  },
];
