/**
 * Hosted MCP endpoint — Hono router that mounts on the existing per-region
 * API server (#2024 / #2028).
 *
 * Self-hosted users connect via stdio (the bunx installer in @useatlas/mcp).
 * SaaS users connect via this hosted endpoint:
 *
 *   POST   /mcp/{workspace_id}/sse   — JSON-RPC frames
 *   GET    /mcp/{workspace_id}/sse   — SSE notifications
 *   DELETE /mcp/{workspace_id}/sse   — explicit session termination
 *
 * Why a router (not a separate service):
 *   - The work MCP does (semantic-layer reads, executeSQL) already runs on
 *     the api/api-eu/api-apac instances. Mounting MCP as a route colocates
 *     it with the data path and inherits the existing per-region residency
 *     guarantees from 1.0.0.
 *   - Per-region routing is enforced by `detectMisrouting()` from the
 *     residency module — workspaces in EU never get served by US even via
 *     the agent path. We fire 421 unconditionally on misrouting (ignoring
 *     `strictRouting`) because the residency promise is not optional for
 *     the MCP surface.
 *
 * Why path-scoped by workspace ID:
 *   - The bearer already names the workspace (PR A's
 *     `lookupMcpTokenByBearer` resolves `org_id`). The path param exists
 *     so an attacker who steals a token from workspace A cannot point the
 *     same bearer at workspace B's URL and probe for inconsistent
 *     behavior — mismatch is 403, not 404, and never leaks whether the
 *     workspace exists.
 *
 * Session ownership:
 *   - Each new session creates a fresh `McpServer` bound to the bearer's
 *     identity (`createAtlasMcpServer({ actor: bearerUser })`). The
 *     server lives for the duration of the session; the per-session
 *     transport handles JSON-RPC dispatch internally.
 *   - The bearer's identity is captured at session-init and reused for
 *     every JSON-RPC frame in that session. A session never crosses
 *     identities even if the same bearer is reused across sessions.
 *
 * Audit emission:
 *   - `mcp_token.use` is fired once per session, on session-init — NOT
 *     per JSON-RPC frame. Rationale: a single Claude Desktop connection
 *     can issue thousands of frames per session; per-frame emission
 *     would drown the audit log without adding signal. Forensics use
 *     "first time this token was used" not "list every frame."
 *
 * Issue: #2024 (PR B of E), #2028 (residency).
 */

import { Hono } from "hono";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { WebStandardStreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js";
import { mcpBearerAuth } from "@atlas/api/api/routes/mcp-middleware";
import type { AuthEnv } from "@atlas/api/api/routes/middleware";
import {
  detectMisrouting,
  getApiRegion,
} from "@atlas/api/lib/residency/misrouting";
import { withRequestContext } from "@atlas/api/lib/logger";
import { createLogger } from "@atlas/api/lib/logger";
import { logAdminAction, ADMIN_ACTIONS } from "@atlas/api/lib/audit";
import { createAtlasMcpServer } from "./server.js";

const log = createLogger("mcp-hosted");

// ── Module-scoped session store ────────────────────────────────────
//
// One Map for the lifetime of the API process. The transport's
// `onsessioninitialized` callback adds entries; `onsessionclosed` and
// the transport's `onclose` hook remove them. The session ID is
// generated by the SDK transport and round-tripped to the client via
// the `mcp-session-id` response header.

interface SessionEntry {
  readonly transport: WebStandardStreamableHTTPServerTransport;
  readonly server: McpServer;
}

const sessions = new Map<string, SessionEntry>();

const DEFAULT_MAX_SESSIONS = 100;

function maxSessions(): number {
  const raw = process.env.ATLAS_MCP_MAX_SESSIONS;
  if (!raw) return DEFAULT_MAX_SESSIONS;
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isFinite(parsed) || parsed < 1) {
    log.warn(
      { raw },
      "ATLAS_MCP_MAX_SESSIONS is not a positive integer — falling back to default",
    );
    return DEFAULT_MAX_SESSIONS;
  }
  return parsed;
}

/**
 * Read-only session count for /health surfaces and tests. Not exported
 * to admin routes — the count is process-local and would be misleading
 * across a pool of api instances.
 */
export function _hostedSessionCount(): number {
  return sessions.size;
}

/** @internal Reset the session store — for tests only. */
export async function _resetHostedSessions(): Promise<void> {
  const entries = [...sessions.entries()];
  sessions.clear();
  for (const [, entry] of entries) {
    await entry.transport.close().catch(() => {});
    await entry.server.close().catch(() => {});
  }
}

// ── Misrouting → 421 ───────────────────────────────────────────────
//
// The standard middleware (`checkMisrouting` in routes/middleware.ts)
// only fires 421 when `strictRouting` is enabled — graceful mode
// serves cross-region requests but logs a warning. MCP cannot defer
// to that flag: workspace data must not cross residency boundaries
// even via the agent path. So we call `detectMisrouting()` directly
// and treat any non-null result as 421, regardless of strict mode.

interface MisroutedResponse {
  readonly status: 421;
  readonly body: {
    error: "misdirected_request";
    message: string;
    correctApiUrl?: string;
    expectedRegion: string;
    actualRegion: string;
    requestId: string;
  };
}

async function checkResidency(
  orgId: string,
  requestId: string,
): Promise<MisroutedResponse | null> {
  const result = await detectMisrouting(orgId, requestId);
  if (!result) return null;
  return {
    status: 421,
    body: {
      error: "misdirected_request",
      message: `MCP requests for this workspace must be directed to the ${result.expectedRegion} region.`,
      ...(result.correctApiUrl !== undefined
        ? { correctApiUrl: result.correctApiUrl }
        : {}),
      expectedRegion: result.expectedRegion,
      actualRegion: result.actualRegion,
      requestId,
    },
  };
}

// ── Audit emission on session-init ──────────────────────────────────

function emitTokenUseAudit(
  tokenId: string,
  orgId: string,
  sessionId: string,
  region: string | null,
): void {
  // Fire-and-forget per the contract in admin/actions.ts:
  //   "mcp_token.use is sampled (per-session, not per-call)."
  // The actor is pulled from `getRequestContext()` via AsyncLocalStorage —
  // we wrap the session-init dispatch in `withRequestContext` so the
  // bearer's user lands on the audit row's actor_id field.
  logAdminAction({
    actionType: ADMIN_ACTIONS.mcp_token.use,
    targetType: "mcp_token",
    targetId: tokenId,
    metadata: {
      sessionId,
      orgId,
      ...(region !== null ? { region } : {}),
    },
  });
}

// ── Per-session MCP server factory ──────────────────────────────────
//
// Each new session gets its own MCP server bound to the bearer's
// identity. The same identity is reused for every JSON-RPC frame in
// the session — the bearer is verified on every HTTP request by the
// middleware, so the session-bound identity matches the live request.

interface InitialFactoryContext {
  readonly user: import("@atlas/api/lib/auth/types").AtlasUser;
  readonly orgId: string;
  readonly tokenId: string;
}

async function createBoundMcpServer(
  ctx: InitialFactoryContext,
): Promise<McpServer> {
  return createAtlasMcpServer({
    actor: ctx.user,
    transport: "sse",
    // The api server boots config eagerly via buildAppLayer — skip
    // re-init on every session-create.
    skipConfig: true,
  });
}

// ── Request dispatch ────────────────────────────────────────────────

async function dispatchExistingSession(
  req: Request,
  sessionId: string,
): Promise<Response> {
  const entry = sessions.get(sessionId);
  if (!entry) {
    // Session ID claimed but unknown to this instance. Could be stale
    // (server restart, sticky-routing miss) or forged. Either way 404
    // is the right answer — no enumeration oracle, client retries with
    // a fresh initialize.
    return new Response("Session not found", { status: 404 });
  }
  return entry.transport.handleRequest(req);
}

async function dispatchNewSession(
  req: Request,
  ctx: InitialFactoryContext,
): Promise<Response> {
  if (sessions.size >= maxSessions()) {
    return new Response(
      JSON.stringify({
        error: "too_many_sessions",
        message: "Too many active MCP sessions on this region. Try again later.",
      }),
      { status: 503, headers: { "Content-Type": "application/json" } },
    );
  }

  const mcpServer = await createBoundMcpServer(ctx);
  const region = getApiRegion();

  const transport = new WebStandardStreamableHTTPServerTransport({
    sessionIdGenerator: () => crypto.randomUUID(),
    onsessioninitialized: (id) => {
      sessions.set(id, { transport, server: mcpServer });
      // Emit audit exactly once when the session is established. Per
      // PR A's contract this is sampled — never per-frame.
      emitTokenUseAudit(ctx.tokenId, ctx.orgId, id, region);
      log.info(
        { sessionId: id, orgId: ctx.orgId, tokenId: ctx.tokenId, region },
        "MCP session created",
      );
    },
    onsessionclosed: (id) => {
      const entry = sessions.get(id);
      if (entry) {
        sessions.delete(id);
        entry.server.close().catch((err) => {
          log.warn(
            {
              sessionId: id,
              err: err instanceof Error ? err.message : String(err),
            },
            "Failed to close per-session MCP server",
          );
        });
      }
    },
  });

  transport.onclose = () => {
    const sid = transport.sessionId;
    if (sid && sessions.has(sid)) {
      const entry = sessions.get(sid)!;
      sessions.delete(sid);
      // intentionally ignored: best-effort cleanup on transport close
      entry.server.close().catch(() => {});
    }
  };

  try {
    await mcpServer.connect(transport);
  } catch (err) {
    // intentionally ignored: best-effort cleanup before re-throwing
    await transport.close().catch(() => {});
    await mcpServer.close().catch(() => {});
    throw err;
  }

  return transport.handleRequest(req);
}

// ── Router ──────────────────────────────────────────────────────────

const HANDLED_METHODS = ["POST", "GET", "DELETE"];

/**
 * Build the hosted MCP Hono router. Mounts at `/mcp` from the api index
 * so the full path is `/mcp/{workspaceId}/sse`.
 *
 * `mcpBearerAuth` is applied router-wide. The handler then enforces the
 * path-vs-bearer workspace match, runs the residency check, and
 * dispatches to the SDK transport.
 */
export function createHostedMcpRouter(): Hono<AuthEnv> {
  const router = new Hono<AuthEnv>();

  router.use("*", mcpBearerAuth);

  router.on(HANDLED_METHODS, "/:workspaceId/sse", async (c) => {
    const requestId = c.get("requestId");
    const authResult = c.get("authResult");
    const user = authResult.user;
    const bearerOrgId = user?.activeOrganizationId;
    const tokenId =
      typeof user?.claims?.mcpTokenId === "string"
        ? user.claims.mcpTokenId
        : null;

    // Defensive — `mcpBearerAuth` guarantees both fields are set, but a
    // future refactor that loosens that contract should fail loud.
    if (!bearerOrgId || !tokenId) {
      log.error(
        { requestId },
        "MCP bearer middleware authenticated without orgId/tokenId — refusing to dispatch",
      );
      return c.json(
        {
          error: "auth_error",
          message: "MCP authentication system error",
          requestId,
        },
        500,
      );
    }

    const pathWorkspaceId = c.req.param("workspaceId");

    // Path/bearer mismatch — opaque 403. Don't 404 (would leak whether
    // the path workspace exists), don't 401 (the bearer IS valid, just
    // not for this URL). Generic message — same as the bearer's
    // INVALID_MCP_TOKEN string for symmetry against probing.
    if (pathWorkspaceId !== bearerOrgId) {
      log.warn(
        {
          requestId,
          bearerOrgId,
          pathWorkspaceId,
          tokenId,
        },
        "MCP path/bearer workspace mismatch — refusing dispatch",
      );
      return c.json(
        {
          error: "forbidden",
          message: "MCP token not authorized for this workspace.",
          requestId,
        },
        403,
      );
    }

    // Residency — fire 421 unconditionally on cross-region. Workspace
    // data must not be served from the wrong region even via the
    // agent path.
    const misrouted = await checkResidency(bearerOrgId, requestId);
    if (misrouted) {
      return c.json(misrouted.body, misrouted.status);
    }

    // Wrap dispatch in `withRequestContext` so the audit emission and
    // any tool-side `getRequestContext()` reads find the bearer's
    // identity.
    const sessionId = c.req.raw.headers.get("mcp-session-id");

    let response: Response;
    try {
      response = await withRequestContext(
        { requestId, user, atlasMode: "published" },
        async () => {
          if (sessionId) {
            return dispatchExistingSession(c.req.raw, sessionId);
          }
          return dispatchNewSession(c.req.raw, {
            user,
            orgId: bearerOrgId,
            tokenId,
          });
        },
      );
    } catch (err) {
      log.error(
        {
          requestId,
          orgId: bearerOrgId,
          err: err instanceof Error ? err.message : String(err),
        },
        "MCP dispatch failed",
      );
      return c.json(
        {
          error: "internal_error",
          message: "MCP request handling failed.",
          requestId,
        },
        500,
      );
    }

    // The SDK transport returns a Response — mirror its body/status
    // verbatim. Hono will compose the api-wide CORS + security
    // headers on top via the surrounding middleware in
    // `packages/api/src/api/index.ts`.
    return response;
  });

  return router;
}
