#!/usr/bin/env bash
# check-oauth-helper-drift.sh — CI gate that asserts the vendored
# `plugins/mcp/src/_oauth-helper/` matches the canonical
# `packages/oauth-helper/src/`.
#
# The vendor script (`plugins/mcp/scripts/vendor-oauth-helper.sh`) runs
# on every `bun install` and `npm publish`, but a contributor editing
# the vendored copy directly between installs would silently diverge —
# their edits would be overwritten on the next install (data loss) or,
# worse, would land in a published `@useatlas/mcp` artifact between
# installs (production drift). This check catches both cases.
#
# Strategy: re-run the vendor script into a tmp directory and diff the
# regenerated tree against the committed-or-installed vendored copy.
# A clean `diff -r` exit means the vendored source is in lockstep with
# the canonical source.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CANONICAL="$ROOT/packages/oauth-helper/src"
VENDORED="$ROOT/plugins/mcp/src/_oauth-helper"

if [ ! -d "$CANONICAL" ]; then
  echo "check-oauth-helper-drift: canonical source missing at $CANONICAL" >&2
  exit 1
fi

if [ ! -d "$VENDORED" ]; then
  echo "check-oauth-helper-drift: vendored copy missing at $VENDORED" >&2
  echo "check-oauth-helper-drift: run \`bun install\` from the repo root to regenerate" >&2
  exit 1
fi

# Regenerate into a tmp dir using the same vendor script the prepare
# hook runs. We can't write to a tmpdir directly (the script writes
# into a fixed path), so we run the script normally then diff against
# a freshly-checked-out copy of the canonical tree.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Mirror the canonical source tree into TMP with the same AUTO-GENERATED
# header the vendor script injects, so the diff is meaningful.
HEADER='// AUTO-GENERATED — DO NOT EDIT.
// Canonical source: packages/oauth-helper/src/
// Regenerated by plugins/mcp/scripts/vendor-oauth-helper.sh on every
// `bun install` and `npm publish`. Edits made here are overwritten.
'

while IFS= read -r -d '' rel; do
  rel_path="${rel#./}"
  target="$TMP/$rel_path"
  mkdir -p "$(dirname "$target")"
  {
    printf '%s' "$HEADER"
    cat "$CANONICAL/$rel_path"
  } > "$target"
done < <(cd "$CANONICAL" && find . -type f -name "*.ts" -print0)

# Diff TMP against the vendored tree, ignoring the auto-generated
# README the vendor script also drops in (it has no canonical mirror).
DRIFT=0
diff_output=$(diff -r --exclude=README.md "$TMP" "$VENDORED" 2>&1) || DRIFT=1

if [ "$DRIFT" -ne 0 ]; then
  echo "check-oauth-helper-drift: vendored copy diverges from canonical source" >&2
  echo "" >&2
  echo "$diff_output" >&2
  echo "" >&2
  echo "Fix: edit the canonical source at packages/oauth-helper/src/," >&2
  echo "then run \`bash plugins/mcp/scripts/vendor-oauth-helper.sh\` (or" >&2
  echo "any \`bun install\` from the repo root)." >&2
  exit 1
fi

echo "OK: vendored _oauth-helper matches canonical packages/oauth-helper/src"
