#!/usr/bin/env bash
# check-openapi-drift.sh — CI check that verifies the generated OpenAPI spec
# and api-reference MDX match the route definitions in packages/api.
#
# Route handlers in packages/api use @hono/zod-openapi createRoute() to declare
# their schemas. apps/docs/openapi.json is regenerated by bun run openapi:extract.
# The api-reference MDX under apps/docs/content/docs/api-reference/ is then
# regenerated from that JSON by bun run --filter @atlas/docs generate:api.
#
# This script:
#   1. Runs openapi:extract in packages/api (writes apps/docs/openapi.json)
#   2. Runs generate:api in apps/docs (writes api-reference MDX)
#   3. Fails if the working tree has changes under apps/docs/openapi.json or
#      apps/docs/content/docs/api-reference/ — meaning a PR modified a route
#      but didn't regenerate the spec + docs.
#
# Run locally: bash scripts/check-openapi-drift.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."

cd "$ROOT"

echo ":: Extracting OpenAPI spec from packages/api..."
bun run --filter '@atlas/api' openapi:extract >/dev/null

echo ":: Regenerating api-reference MDX from apps/docs/openapi.json..."
bun run --filter '@atlas/docs' generate:api >/dev/null

echo ":: Checking for drift..."
DRIFT=$(git status --porcelain -- apps/docs/openapi.json apps/docs/content/docs/api-reference || true)

if [[ -n "$DRIFT" ]]; then
  echo ""
  echo "ERROR: OpenAPI spec or api-reference MDX is out of date."
  echo "A route in packages/api was changed without regenerating the spec + docs."
  echo ""
  echo "Drifted files:"
  echo "$DRIFT"
  echo ""
  echo "To fix:"
  echo "  bun run --filter '@atlas/api' openapi:extract"
  echo "  bun run --filter '@atlas/docs' generate:api"
  echo "  git add apps/docs/openapi.json apps/docs/content/docs/api-reference"
  exit 1
fi

echo "OpenAPI drift check passed — spec and api-reference are in sync with routes."
