#!/usr/bin/env bash
# check-saas-env-doc.sh — CI check that the generated SaaS env-var table in
# the operator reference is in sync with the SAAS_ENV_KEYS SSOT (#3707).
#
# SAAS_ENV_KEYS in packages/api/src/lib/effect/saas-env.ts is the
# compile-time-exhaustive list of every env var the SaaS-mode boot contract
# reads. The authoritative table in
# apps/docs/content/docs/platform-ops/saas-environment-variables.mdx is
# machine-generated from it by scripts/generate-saas-env-doc.ts.
#
# This script:
#   1. Runs the generator (rewrites the table between the
#      <auto-generated:saas-env-keys> markers in the MDX)
#   2. Fails if the working tree now shows changes to that MDX — meaning a
#      var was added/removed/renamed in SAAS_ENV_KEYS (or KEY_META in the
#      generator) without regenerating the doc.
#
# The generator itself hard-fails if KEY_META and SAAS_ENV_KEYS diverge (a new
# SSOT key with no description), so this gate catches both "forgot to add a
# description" and "forgot to regenerate".
#
# Run locally: bash scripts/check-saas-env-doc.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."

cd "$ROOT"

DOC="apps/docs/content/docs/platform-ops/saas-environment-variables.mdx"

echo ":: Regenerating SaaS env table from SAAS_ENV_KEYS..."
bun scripts/generate-saas-env-doc.ts

echo ":: Checking for drift..."
# No `|| true` — if git fails (missing binary, corrupt repo, bad pathspec), fail
# the gate rather than silently report "no drift". `set -e` propagates non-zero.
DRIFT=$(git status --porcelain -- "$DOC")

if [[ -n "$DRIFT" ]]; then
  echo ""
  echo "ERROR: The SaaS env reference table is out of date."
  echo "SAAS_ENV_KEYS (or the generator's KEY_META) changed without"
  echo "regenerating $DOC."
  echo ""
  echo "Drifted file:"
  echo "$DRIFT"
  echo ""
  echo "To fix:"
  echo "  bun scripts/generate-saas-env-doc.ts"
  echo "  git add $DOC"
  exit 1
fi

echo "SaaS env doc check passed — operator table is in sync with SAAS_ENV_KEYS."
