#!/usr/bin/env bun
/**
 * Generate the SaaS operator env-var table in
 * `apps/docs/content/docs/platform-ops/saas-environment-variables.mdx`
 * from the `SAAS_ENV_KEYS` SSOT (#3707).
 *
 * `SAAS_ENV_KEYS` in `packages/api/src/lib/effect/saas-env.ts` is the
 * compile-time-exhaustive list of every env var the SaaS-mode boot
 * contract reads. The operator reference must not be able to drift from
 * it, so the authoritative table is machine-generated between the
 * `<auto-generated:saas-env-keys>` markers in the MDX. Surrounding prose
 * (the curated breakdowns, the runtime-settings section) is hand-written
 * and left untouched.
 *
 * This script reads `SAAS_ENV_KEYS`, validates that {@link KEY_META} has
 * an entry for exactly those keys (adding a key to the SSOT without a
 * description here is a hard error), renders the table, and splices it
 * between the markers. `scripts/check-saas-env-doc.sh` runs this and then
 * `git diff`s the MDX — a stale table fails the `drift` CI gate.
 *
 * Run locally: bun scripts/generate-saas-env-doc.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// Relative import: this script lives in the repo root scripts/ dir,
// where the @atlas/api workspace alias is not resolvable (root has no
// dependency on it). Same constraint as scripts/saas-env-fixture.ts.
import { SAAS_ENV_KEYS } from "../packages/api/src/lib/effect/saas-env";

type SaasEnvKey = (typeof SAAS_ENV_KEYS)[number];

interface KeyMeta {
  /** Logical grouping, shown verbatim in the "Category" column. */
  readonly category: string;
  /** One-line operator-facing description (no unescaped `|`). */
  readonly purpose: string;
}

/**
 * Per-key category + purpose. Must cover exactly `SAAS_ENV_KEYS` — the
 * generator throws if a key is missing or extra, so adding a var to the
 * SSOT forces a description here. Phrasing mirrors the grouping comments
 * in `saas-env.ts`; keep it accurate to the guard that reads each key.
 */
const KEY_META: Record<SaasEnvKey, KeyMeta> = {
  DATABASE_URL: {
    category: "Internal database",
    purpose:
      "Internal Postgres for auth, audit, settings, billing (`InternalDbGuardLive`, `MigrationGuardLive`).",
  },
  ATLAS_DATASOURCE_URL: {
    category: "Analytics datasource",
    purpose:
      "Default analytics datasource Atlas queries (read-only). Customer datasources are added per-workspace in Admin.",
  },
  ATLAS_ENCRYPTION_KEYS: {
    category: "Encryption & session secrets",
    purpose:
      "At-rest credential encryption keyset (`v<N>:<base64>`). `EncryptionKeyGuardLive`.",
  },
  ATLAS_ENCRYPTION_KEY: {
    category: "Encryption & session secrets",
    purpose:
      "Legacy single-key fallback for at-rest encryption; `ATLAS_ENCRYPTION_KEYS` supersedes it.",
  },
  BETTER_AUTH_SECRET: {
    category: "Encryption & session secrets",
    purpose: "Better Auth session-signing secret (≥32 chars).",
  },
  ATLAS_RATE_LIMIT_RPM: {
    category: "Rate limiting",
    purpose:
      "Base requests-per-minute floor. `RateLimitGuardLive` refuses to boot a region without a positive value.",
  },
  ATLAS_PROVIDER: {
    category: "LLM provider",
    purpose:
      "Selects the LLM provider. Unset → `getDefaultProvider()` (`gateway` on SaaS).",
  },
  AI_GATEWAY_API_KEY: {
    category: "LLM provider",
    purpose:
      "Vercel AI Gateway key for the SaaS gateway default. `ProviderKeyGuardLive` requires it (or whichever provider key `ATLAS_PROVIDER` resolves to).",
  },
  ATLAS_API_REGION: {
    category: "Region routing",
    purpose:
      "This instance's region identity (`us` / `eu` / `apac` / `staging`). `RegionGuardLive`.",
  },
  ATLAS_REGION_US_DB_URL: {
    category: "Region routing",
    purpose: "US region internal Postgres URL for residency routing.",
  },
  ATLAS_REGION_EU_DB_URL: {
    category: "Region routing",
    purpose: "EU region internal Postgres URL for residency routing.",
  },
  ATLAS_REGION_APAC_DB_URL: {
    category: "Region routing",
    purpose: "APAC region internal Postgres URL for residency routing.",
  },
  ATLAS_STRICT_PLUGIN_SECRETS: {
    category: "Plugin config",
    purpose:
      "Strict mode: fail boot on a missing plugin secret rather than silently dropping the plugin. `PluginConfigGuardLive`.",
  },
  ATLAS_SMTP_URL: {
    category: "Platform email (DPA)",
    purpose:
      "SMTP URL for platform transactional email — alternative to `RESEND_API_KEY`. DPA-gated by `DpaGuardLive`.",
  },
  RESEND_API_KEY: {
    category: "Platform email (DPA)",
    purpose:
      "Resend API key for platform transactional email. SaaS platform email must be Resend (DPA).",
  },
  BETTER_AUTH_URL: {
    category: "Auth boot inputs",
    purpose:
      "Better Auth base URL — read inside the library's plugin init before settings load.",
  },
  BETTER_AUTH_TRUSTED_ORIGINS: {
    category: "Auth boot inputs",
    purpose:
      "Anchors verification / password-reset redirects to the web origin (also seeds `getWebOrigin()`).",
  },
  SLACK_SIGNING_SECRET: {
    category: "Slack adapter",
    purpose: "Slack request-signature secret (32-char lowercase hex).",
  },
  SLACK_CLIENT_ID: {
    category: "Slack adapter",
    purpose: "Atlas's own Slack app OAuth client ID.",
  },
  SLACK_CLIENT_SECRET: {
    category: "Slack adapter",
    purpose: "Atlas's own Slack app OAuth client secret.",
  },
  SLACK_ENCRYPTION_KEY: {
    category: "Slack adapter",
    purpose:
      "At-rest key for stored Slack installation credentials. A missing one silently drops the adapter — `ChatAdapterEnvGuardLive` now boot-blocks.",
  },
};

const MARKER_START =
  "{/* <auto-generated:saas-env-keys> Do not edit by hand — run `bun scripts/generate-saas-env-doc.ts` */}";
const MARKER_END = "{/* </auto-generated:saas-env-keys> */}";

const DOC_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "apps/docs/content/docs/platform-ops/saas-environment-variables.mdx",
);

/** Throw unless KEY_META covers exactly the SSOT keys (no missing, no extra). */
function assertMetaExhaustive(): void {
  const metaKeys = Object.keys(KEY_META);
  const missing = SAAS_ENV_KEYS.filter((k) => !(k in KEY_META));
  const extra = metaKeys.filter(
    (k) => !SAAS_ENV_KEYS.includes(k as SaasEnvKey),
  );
  if (missing.length > 0 || extra.length > 0) {
    const parts: string[] = [];
    if (missing.length > 0) {
      parts.push(`missing KEY_META for: ${missing.join(", ")}`);
    }
    if (extra.length > 0) {
      parts.push(`KEY_META has stale key(s) not in SAAS_ENV_KEYS: ${extra.join(", ")}`);
    }
    throw new Error(
      `KEY_META is out of sync with SAAS_ENV_KEYS — ${parts.join("; ")}. ` +
        `Update KEY_META in scripts/generate-saas-env-doc.ts.`,
    );
  }

  // A literal `|` in a cell would silently break the markdown table render
  // rather than error. Reject it here so the failure is loud, not visual.
  const piped = SAAS_ENV_KEYS.filter(
    (k) => KEY_META[k].category.includes("|") || KEY_META[k].purpose.includes("|"),
  );
  if (piped.length > 0) {
    throw new Error(
      `KEY_META contains an unescaped \`|\` (breaks the markdown table) for: ` +
        `${piped.join(", ")}. Remove or escape it in scripts/generate-saas-env-doc.ts.`,
    );
  }
}

/** Render the markdown table, one row per SSOT key in SSOT order. */
function renderTable(): string {
  const header = "| Variable | Category | Purpose |\n|---|---|---|";
  const rows = SAAS_ENV_KEYS.map((key) => {
    const meta = KEY_META[key];
    return `| \`${key}\` | ${meta.category} | ${meta.purpose} |`;
  });
  return [header, ...rows].join("\n");
}

function main(): void {
  // `--check` verifies the generated block is current without writing, and
  // without consulting git — so it ignores in-progress edits to the curated
  // prose *outside* the markers (which the generator leaves untouched and
  // which `git status` would otherwise flag as spurious drift).
  const checkOnly = process.argv.includes("--check");

  assertMetaExhaustive();

  const source = readFileSync(DOC_PATH, "utf8");
  const startIdx = source.indexOf(MARKER_START);
  const endIdx = source.indexOf(MARKER_END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Generated-block markers not found (or out of order) in ${DOC_PATH}. ` +
        `Expected ${MARKER_START} ... ${MARKER_END}.`,
    );
  }

  const before = source.slice(0, startIdx);
  const after = source.slice(endIdx + MARKER_END.length);
  const block = `${MARKER_START}\n\n${renderTable()}\n\n${MARKER_END}`;
  const next = `${before}${block}${after}`;

  if (next === source) {
    process.stdout.write(
      `generate-saas-env-doc: SaaS env table already up to date (${SAAS_ENV_KEYS.length} keys).\n`,
    );
    return;
  }

  if (checkOnly) {
    throw new Error(
      `SaaS env table is out of date — the generated block in ${DOC_PATH} ` +
        `does not match SAAS_ENV_KEYS/KEY_META. Run \`bun scripts/generate-saas-env-doc.ts\` and commit.`,
    );
  }

  writeFileSync(DOC_PATH, next);
  process.stdout.write(
    `generate-saas-env-doc: regenerated SaaS env table (${SAAS_ENV_KEYS.length} keys).\n`,
  );
}

try {
  main();
} catch (err) {
  const message = err instanceof Error ? err.message : String(err);
  process.stderr.write(`generate-saas-env-doc: ${message}\n`);
  process.exit(1);
}
