#!/usr/bin/env bash
set -euo pipefail

# sync-starter.sh
#
# Generates a trimmed version of the monorepo's nextjs-standalone template
# for the AtlasDevHQ/atlas-starter repo. Strips heavy DB adapters (ClickHouse,
# Snowflake, DuckDB, Salesforce), scheduler, and admin UI.
#
# Usage: scripts/sync-starter.sh [output-dir]
#   output-dir  defaults to /tmp/atlas-starter-sync

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
OUTPUT="${1:-/tmp/atlas-starter-sync}"

echo ":: sync-starter: output → $OUTPUT"

# ── Step 1: Generate template source ─────────────────────────────────
echo ":: Running prepare-templates.sh..."
SKIP_SYNCPACK=1 bash "$ROOT/create-atlas/scripts/prepare-templates.sh"
# Note: SKIP_SYNCPACK is checked in prepare-templates.sh to skip syncpack lint/fix

TEMPLATE="$ROOT/create-atlas/templates/nextjs-standalone"

# ── Step 2: Copy template to staging ─────────────────────────────────
echo ":: Copying template to staging..."
rm -rf "$OUTPUT"
mkdir -p "$OUTPUT"

# Source files (generated by prepare-templates.sh)
cp -r "$TEMPLATE/src" "$OUTPUT/src"
cp -r "$TEMPLATE/bin" "$OUTPUT/bin"
cp -r "$TEMPLATE/data" "$OUTPUT/data"
cp -r "$TEMPLATE/docs" "$OUTPUT/docs"

# Static template files
cp "$TEMPLATE/eslint.config.mjs"  "$OUTPUT/eslint.config.mjs"
cp "$TEMPLATE/next.config.ts"     "$OUTPUT/next.config.ts"
cp "$TEMPLATE/postcss.config.mjs" "$OUTPUT/postcss.config.mjs"
cp "$TEMPLATE/tsconfig.json"      "$OUTPUT/tsconfig.json"
cp "$TEMPLATE/package.json"       "$OUTPUT/package.json"

# global-error.tsx from examples/nextjs-standalone (not generated by prepare-templates)
if [ -f "$ROOT/examples/nextjs-standalone/src/app/global-error.tsx" ]; then
  cp "$ROOT/examples/nextjs-standalone/src/app/global-error.tsx" "$OUTPUT/src/app/"
else
  echo ":: Note: global-error.tsx not found in examples/nextjs-standalone — skipping"
fi

# ── Step 3: Remove excluded files/directories ────────────────────────
echo ":: Applying exclusions..."

# Scheduler (source + tests)
rm -rf "$OUTPUT/src/lib/scheduler"
rm -f  "$OUTPUT/src/lib/scheduled-task-types.ts"
rm -f  "$OUTPUT/src/lib/scheduled-tasks.ts"
rm -f  "$OUTPUT/src/api/routes/scheduled-tasks.ts"
rm -f  "$OUTPUT/src/api/__tests__/scheduled-tasks.test.ts"
rm -f  "$OUTPUT/src/lib/__tests__/scheduled-task-types.test.ts"
rm -f  "$OUTPUT/src/lib/__tests__/scheduled-tasks.test.ts"

# Salesforce (source + tests)
rm -f "$OUTPUT/src/lib/tools/salesforce.ts"
rm -f "$OUTPUT/src/lib/tools/soql-validation.ts"
rm -f "$OUTPUT/src/lib/db/salesforce.ts"
rm -f "$OUTPUT/src/lib/db/__tests__/salesforce.test.ts"
rm -f "$OUTPUT/src/lib/tools/__tests__/salesforce-tool.test.ts"

# DuckDB (source + tests)
rm -f "$OUTPUT/src/lib/db/duckdb.ts"
rm -f "$OUTPUT/src/lib/db/__tests__/duckdb.test.ts"
rm -f "$OUTPUT/src/lib/db/__tests__/snowflake.test.ts"
rm -f "$OUTPUT/src/lib/tools/__tests__/sql-duckdb.test.ts"

# Admin UI + hooks
rm -rf "$OUTPUT/src/ui/components/admin"
rm -f  "$OUTPUT/src/ui/hooks/use-admin-fetch.ts"

# ── Pre-transform validation ──────────────────────────────────────────
echo ":: Validating template output..."
conn="$OUTPUT/src/lib/db/connection.ts"
api_index="$OUTPUT/src/api/index.ts"
for f in "$conn" "$api_index" "$OUTPUT/src/app/globals.css" "$OUTPUT/next.config.ts" "$OUTPUT/package.json"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: Expected file not found: $f" >&2
    echo "       prepare-templates.sh may have failed or changed output structure." >&2
    exit 1
  fi
done

# ── Step 4: Transform connection.ts ──────────────────────────────────
echo ":: Transforming connection.ts (PostgreSQL + MySQL only)..."

# 4a. Remove function blocks (with preceding JSDoc) using awk.
# Top-level functions in connection.ts always close with ^} (column 0).
# JSDoc comments (/** ... */) immediately before a function are also removed.
awk '
# Buffer JSDoc comments so we can discard them if the next function is excluded.

# Single-line JSDoc: /** ... */ on one line
/^\/\*\*/ && /\*\// {
  pending_jsdoc = $0 "\n"
  next
}
# Multi-line JSDoc start: /**
/^\/\*\*/ {
  in_jsdoc = 1
  jsdoc_buf = $0 "\n"
  next
}
in_jsdoc && !/\*\// {
  jsdoc_buf = jsdoc_buf $0 "\n"
  next
}
in_jsdoc && /\*\// {
  in_jsdoc = 0
  jsdoc_buf = jsdoc_buf $0 "\n"
  pending_jsdoc = jsdoc_buf
  jsdoc_buf = ""
  next
}

# Blank lines between JSDoc and function — keep buffering
pending_jsdoc != "" && /^$/ {
  pending_jsdoc = pending_jsdoc "\n"
  next
}

# Function to skip (with preceding JSDoc)? Discard JSDoc and enter skip mode
pending_jsdoc != "" && /^(export )?function (rewriteClickHouseUrl|createClickHouseDB|parseSnowflakeURL|createSnowflakeDB)\(/ {
  pending_jsdoc = ""
  skip = 1
  next
}

# Not a skipped function — flush pending JSDoc
pending_jsdoc != "" {
  printf "%s", pending_jsdoc
  pending_jsdoc = ""
}

# Function to skip (no JSDoc)? Enter skip mode
/^(export )?function (rewriteClickHouseUrl|createClickHouseDB|parseSnowflakeURL|createSnowflakeDB)\(/ {
  skip = 1
  next
}

# While skipping a function block, wait for closing brace at column 0.
# Top-level functions in connection.ts always close with ^} — this is
# more robust than brace-counting which can be fooled by braces in strings.
skip && /^\}/ { skip = 0; next }
skip { next }

# Skip duckdb import
/^import.*from "\.\/duckdb"/ { next }

# All other lines: print
{ print }

END {
  # Flush any trailing JSDoc
  if (pending_jsdoc != "") printf "%s", pending_jsdoc
}
' "$conn" > "$conn.tmp" && mv "$conn.tmp" "$conn"

# 4b. Simplify DBType union
sed -i 's/export type DBType = "postgres" | "mysql" | "clickhouse" | "snowflake" | "duckdb" | "salesforce"/export type DBType = "postgres" | "mysql"/' "$conn"

# 4c. Simplify extractTargetHost regex
sed -i 's/postgresql|postgres|mysql|mysql2|clickhouse|clickhouses|snowflake|duckdb|salesforce/postgresql|postgres|mysql|mysql2/' "$conn"

# 4d. In detectDBType, remove ClickHouse/Snowflake/DuckDB/Salesforce branches
# Each branch is: if (connStr.startsWith("...")) {\n    return "...";\n  }
sed -i '/connStr\.startsWith("clickhouse/,/^  }/d' "$conn"
sed -i '/connStr\.startsWith("snowflake/,/^  }/d' "$conn"
sed -i '/connStr\.startsWith("duckdb/,/^  }/d' "$conn"
sed -i '/connStr\.startsWith("salesforce/,/^  }/d' "$conn"

# 4e. In createConnection switch, remove extra cases
# clickhouse/snowflake are single-line returns, duckdb is single-line, salesforce is a multi-line throw
sed -i '/^    case "clickhouse":/,/createClickHouseDB/d' "$conn"
sed -i '/^    case "snowflake":/,/createSnowflakeDB/d' "$conn"
sed -i '/^    case "duckdb":/,/createDuckDBConnection/d' "$conn"
sed -i '/^    case "salesforce":/,/^      );$/d' "$conn"

# 4f. Simplify _totalPoolSlots (remove ClickHouse/DuckDB special case)
# The block is: comment + if (clickhouse||duckdb) { total+=1 } else { total+=... }
# Replace the whole if/else with just: total += entry.config?.maxConnections ?? 10;
# Use a single awk pass scoped to the ClickHouse comment to avoid touching healthCheck's } else {
awk '
  /ClickHouse uses a stateless HTTP client/ { in_pool_fix = 1; next }
  in_pool_fix && /neither maintains a connection pool/ { next }
  in_pool_fix && /entry\.dbType === "clickhouse"/ { next }
  in_pool_fix && /total \+= 1;/ { next }
  in_pool_fix && /\} else \{/ { next }
  in_pool_fix && /total \+= entry\.config/ {
    # Re-indent from 8 to 6 spaces
    sub(/^        /, "      ")
    print
    next
  }
  in_pool_fix && /^      \}$/ { in_pool_fix = 0; next }
  { print }
' "$conn" > "$conn.tmp" && mv "$conn.tmp" "$conn"

# 4g. Simplify error messages
# detectDBType: "No database URL provided" error
sed -i 's/"No database URL provided\. Set ATLAS_DATASOURCE_URL to a PostgreSQL.*connection string\."/"No database URL provided. Set ATLAS_DATASOURCE_URL to a PostgreSQL (postgresql:\/\/...) or MySQL (mysql:\/\/...) connection string."/' "$conn"

# detectDBType: "Unsupported database URL scheme" error
sed -i 's/ATLAS_DATASOURCE_URL must start with postgresql:\/\/.*salesforce:\/\/\./ATLAS_DATASOURCE_URL must start with postgresql:\/\/, postgres:\/\/, mysql:\/\/, or mysql2:\/\/./' "$conn"

# getDefault: "No analytics datasource configured" error
sed -i 's/"No analytics datasource configured\. Set ATLAS_DATASOURCE_URL to a PostgreSQL, MySQL.*connection string\."/"No analytics datasource configured. Set ATLAS_DATASOURCE_URL to a PostgreSQL or MySQL connection string."/' "$conn"

# 4h. Simplify file-level JSDoc comment
# The awk step left a blank line where "Supports PostgreSQL..." was.
# Replace the file-level JSDoc header block entirely using awk.
awk '
  # Match the opening of the file-level JSDoc
  NR == 1 && /^\/\*\*/ {
    # Print a clean replacement header
    print "/**"
    print " * Database connection factory and registry."
    print " *"
    print " * Supports PostgreSQL (via `pg` Pool) and MySQL (via `mysql2/promise`)."
    print " * Database type is detected from the connection URL format:"
    print " *   - `postgresql://` or `postgres://` → PostgreSQL"
    print " *   - `mysql://` or `mysql2://` → MySQL"
    # Skip the original header lines until we reach the closing part
    in_header = 1
    next
  }
  in_header && /^ \* Connections are managed/ {
    in_header = 0
    print
    next
  }
  in_header { next }
  { print }
' "$conn" > "$conn.tmp" && mv "$conn.tmp" "$conn"

# Remove any remaining comments about excluded DB types in detectDBType JSDoc
sed -i '/^ \* ClickHouse URLs start with/d' "$conn"
sed -i '/^ \* Snowflake URLs start with/d' "$conn"
sed -i '/^ \* DuckDB URLs start with/d' "$conn"
sed -i '/^ \* Salesforce URLs start with/d' "$conn"

# Simplify ConnectionConfig JSDoc
sed -i 's/Database connection string (postgresql:\/\/.*salesforce:\/\/)\./Database connection string (postgresql:\/\/ or mysql:\/\/)./' "$conn"
sed -i 's/Ignored for MySQL, ClickHouse, Snowflake, and DuckDB\./Ignored for MySQL./' "$conn"

# Clean up runs of consecutive blank lines
cat -s "$conn" > "$conn.tmp" && mv "$conn.tmp" "$conn"

# ── Step 5: Transform api/index.ts ───────────────────────────────────
echo ":: Transforming api/index.ts (removing scheduled-tasks route)..."

# Remove the scheduled-tasks block: from comment through closing }
# Use ^}$ to match the standalone closing brace (not "} else {")
sed -i '/^\/\/ Scheduled tasks routes/,/^}$/d' "$api_index"

# Clean up runs of consecutive blank lines
cat -s "$api_index" > "$api_index.tmp" && mv "$api_index.tmp" "$api_index"

# ── Step 6: Transform globals.css ────────────────────────────────────
echo ":: Transforming globals.css (removing shadcn/tailwind.css import)..."
sed -i '/@import "shadcn\/tailwind\.css";/d' "$OUTPUT/src/app/globals.css"
# Clean up runs of consecutive blank lines
cat -s "$OUTPUT/src/app/globals.css" > "$OUTPUT/src/app/globals.css.tmp" && mv "$OUTPUT/src/app/globals.css.tmp" "$OUTPUT/src/app/globals.css"

# ── Step 7: Transform next.config.ts ─────────────────────────────────
echo ":: Transforming next.config.ts (removing heavy packages)..."
# Remove @clickhouse/client, @duckdb/node-api, snowflake-sdk, jsforce from serverExternalPackages
sed -i 's/, "@clickhouse\/client"//g' "$OUTPUT/next.config.ts"
sed -i 's/, "@duckdb\/node-api"//g' "$OUTPUT/next.config.ts"
sed -i 's/, "snowflake-sdk"//g' "$OUTPUT/next.config.ts"
sed -i 's/, "jsforce"//g' "$OUTPUT/next.config.ts"

# ── Step 8: Transform sql.ts (remove extra DB type branches) ─────────
echo ":: Transforming sql.ts (PostgreSQL + MySQL only)..."
sql_ts="$OUTPUT/src/lib/tools/sql.ts"
if [ -f "$sql_ts" ]; then
  # Remove ClickHouse/Snowflake/DuckDB forbidden pattern constants (multi-line blocks)
  sed -i '/^\/\/ ClickHouse-specific patterns/,/^];$/d' "$sql_ts"
  sed -i '/^\/\/ Snowflake-specific patterns/,/^];$/d' "$sql_ts"
  sed -i '/^\/\/ DuckDB-specific patterns/,/^];$/d' "$sql_ts"
  # Remove extra cases in parserDatabase switch (single-line + multi-line salesforce)
  sed -i '/case "clickhouse": return "PostgresQL";/d' "$sql_ts"
  sed -i '/case "snowflake": return "Snowflake";/d' "$sql_ts"
  sed -i '/case "duckdb": return "PostgresQL";/d' "$sql_ts"
  sed -i '/case "salesforce":/,/);$/{ /case "salesforce":/d; /throw new Error(/d; /Salesforce uses SOQL/d; /);$/d; }' "$sql_ts"
  # Remove comments above deleted cases
  sed -i '/node-sql-parser v5 has no ClickHouse dialect/d' "$sql_ts"
  sed -i '/closest match for ClickHouse SELECT syntax/d' "$sql_ts"
  sed -i "/DuckDB's SQL dialect is PostgreSQL-compatible/d" "$sql_ts"
  sed -i '/CTEs, JOINs, subqueries, window functions/d' "$sql_ts"
  # Remove extra cases in getExtraPatterns switch
  sed -i '/case "clickhouse": return CLICKHOUSE_FORBIDDEN_PATTERNS;/d' "$sql_ts"
  sed -i '/case "snowflake": return SNOWFLAKE_FORBIDDEN_PATTERNS;/d' "$sql_ts"
  sed -i '/case "duckdb": return DUCKDB_FORBIDDEN_PATTERNS;/d' "$sql_ts"
  sed -i '/case "salesforce": return \[\];/d' "$sql_ts"
  # Remove Salesforce redirect block in validateSQL
  sed -i '/\/\/ Salesforce uses SOQL/,/^  }/d' "$sql_ts"
  # Simplify parserDatabase JSDoc
  sed -i '/ClickHouse and DuckDB use PostgreSQL mode/d' "$sql_ts"
  sed -i '/Snowflake uses "Snowflake" mode/d' "$sql_ts"
  # Simplify error messages referencing removed DBs
  sed -i 's/PostgreSQL, MySQL, ClickHouse, Snowflake, DuckDB, or Salesforce/PostgreSQL or MySQL/' "$sql_ts"
  # Clean up
  cat -s "$sql_ts" > "$sql_ts.tmp" && mv "$sql_ts.tmp" "$sql_ts"
fi

# ── Step 8b: Transform agent.ts (remove extra dialect guides) ────────
echo ":: Transforming agent.ts (PostgreSQL + MySQL only)..."
agent_ts="$OUTPUT/src/lib/agent.ts"
if [ -f "$agent_ts" ]; then
  # Remove dialect guide constants (multi-line string literals ending with backtick-semicolon)
  # Each starts with "const X_DIALECT_GUIDE = \`" and ends with a line ending in "\`;"
  awk '
    /^const (CLICKHOUSE_DIALECT_GUIDE|SOQL_DIALECT_GUIDE|SNOWFLAKE_DIALECT_GUIDE|DUCKDB_DIALECT_GUIDE) = `/ {
      skip_template = 1
      next
    }
    skip_template && /`;$/ { skip_template = 0; next }
    skip_template { next }
    { print }
  ' "$agent_ts" > "$agent_ts.tmp" && mv "$agent_ts.tmp" "$agent_ts"
  # Remove extra cases in dialectName switch
  sed -i '/case "clickhouse": return "ClickHouse";/d' "$agent_ts"
  sed -i '/case "snowflake": return "Snowflake";/d' "$agent_ts"
  sed -i '/case "duckdb": return "DuckDB";/d' "$agent_ts"
  sed -i '/case "salesforce": return "Salesforce (SOQL)";/d' "$agent_ts"
  # Remove extra cases in getSystemPrompt switch
  sed -i '/case "clickhouse": return appendDialectHints/d' "$agent_ts"
  sed -i '/case "snowflake": return appendDialectHints/d' "$agent_ts"
  sed -i '/case "duckdb": return appendDialectHints/d' "$agent_ts"
  sed -i '/case "salesforce": return appendDialectHints/d' "$agent_ts"
  # Remove multi-datasource dialect checks
  sed -i '/dbTypes\.has("clickhouse")/d' "$agent_ts"
  sed -i '/dbTypes\.has("snowflake")/d' "$agent_ts"
  sed -i '/dbTypes\.has("duckdb")/d' "$agent_ts"
  sed -i '/dbTypes\.has("salesforce")/d' "$agent_ts"
  # Clean up
  cat -s "$agent_ts" > "$agent_ts.tmp" && mv "$agent_ts.tmp" "$agent_ts"
fi

# ── Step 9: Transform atlas-chat.tsx (remove admin password dialog) ───
echo ":: Transforming atlas-chat.tsx (removing ChangePasswordDialog)..."
atlas_chat="$OUTPUT/src/ui/components/atlas-chat.tsx"
if [ -f "$atlas_chat" ]; then
  # Remove ChangePasswordDialog import
  sed -i '/^import { ChangePasswordDialog } from "\.\/admin\//d' "$atlas_chat"
  # Remove passwordChangeRequired state
  sed -i '/const \[passwordChangeRequired, setPasswordChangeRequired\]/d' "$atlas_chat"
  # Remove useEffect block that checks password-status (from comment through closing })
  sed -i '/\/\/ Check if managed auth user needs to change their default password/,/checkPasswordStatus();/d' "$atlas_chat"
  # Remove the closing of that useEffect: }, [isManaged, ...]);
  sed -i '/isManaged, managedSession\.data?.user, apiUrl, isCrossOrigin\]/d' "$atlas_chat"
  # Remove <ChangePasswordDialog .../> JSX block (3 lines + closing)
  sed -i '/<ChangePasswordDialog/,/\/>/d' "$atlas_chat"
  # Clean up runs of consecutive blank lines
  cat -s "$atlas_chat" > "$atlas_chat.tmp" && mv "$atlas_chat.tmp" "$atlas_chat"
fi

# ── Step 10: Transform package.json ──────────────────────────────────
echo ":: Transforming package.json..."
# Replace template placeholder with starter name
sed -i 's/%PROJECT_NAME%/atlas-starter/' "$OUTPUT/package.json"

# ── Step 11: Post-transform validation ────────────────────────────────
echo ":: Running post-transform validation..."
has_error=0

# Verify removed functions are gone from connection.ts
for fn in rewriteClickHouseUrl createClickHouseDB parseSnowflakeURL createSnowflakeDB; do
  if grep -q "function $fn" "$conn"; then
    echo "ERROR: Function $fn was not removed from connection.ts" >&2
    has_error=1
  fi
done

# Verify DBType was simplified
if grep -q '"clickhouse"\|"snowflake"\|"duckdb"\|"salesforce"' <(grep 'export type DBType' "$conn"); then
  echo "ERROR: DBType union still contains removed database types" >&2
  has_error=1
fi

# Verify no removed DB type switch cases remain (these break TypeScript with never exhaustiveness)
for f in "$OUTPUT/src/lib/tools/sql.ts" "$OUTPUT/src/lib/agent.ts"; do
  if [ -f "$f" ] && grep -q 'case "clickhouse"\|case "snowflake"\|case "duckdb"\|case "salesforce"' "$f"; then
    echo "ERROR: Removed DB type switch cases still present in $(basename "$f")" >&2
    has_error=1
  fi
done

# Verify no references to deleted modules in non-test source files
orphans=$(grep -rl 'import.*scheduler\|import.*scheduled-task\|from.*scheduler\|from.*scheduled-task' "$OUTPUT/src/" --include='*.ts' --include='*.tsx' | grep -v '__tests__' | grep -v '\.test\.' || true)
if [ -n "$orphans" ]; then
  echo "WARNING: Orphaned scheduler imports found in:" >&2
  echo "$orphans" >&2
fi

orphans=$(grep -rl 'import.*\/salesforce\|from.*\/salesforce\|require.*salesforce' "$OUTPUT/src/" --include='*.ts' --include='*.tsx' | grep -v '__tests__' | grep -v '\.test\.' || true)
if [ -n "$orphans" ]; then
  echo "WARNING: Orphaned salesforce imports found in:" >&2
  echo "$orphans" >&2
fi

orphans=$(grep -rl 'import.*\/duckdb\|from.*\/duckdb' "$OUTPUT/src/" --include='*.ts' --include='*.tsx' | grep -v '__tests__' | grep -v '\.test\.' || true)
if [ -n "$orphans" ]; then
  echo "WARNING: Orphaned duckdb imports found in:" >&2
  echo "$orphans" >&2
fi

# Verify no references to deleted admin components (this IS an error — breaks build)
orphans=$(grep -rl 'from.*\/admin\/' "$OUTPUT/src/" --include='*.ts' --include='*.tsx' | grep -v '__tests__' | grep -v '\.test\.' || true)
if [ -n "$orphans" ]; then
  echo "ERROR: Orphaned admin imports found in:" >&2
  echo "$orphans" >&2
  has_error=1
fi

if [ "$has_error" -ne 0 ]; then
  echo "ERROR: Post-transform validation failed. The source file format may have changed." >&2
  exit 1
fi

# ── Done ─────────────────────────────────────────────────────────────
echo ""
echo ":: Sync output ready at $OUTPUT"
echo ":: Files that should be overlaid from atlas-starter (NOT generated):"
echo "::   scripts/seed-demo.ts, scripts/migrate.ts, scripts/setup-demo.sh"
echo "::   vercel.json, README.md, .env.example, .gitignore, semantic/"

