/**
 * The Docusaurus OKF importer (#4392, PRD #4372) — the markdown-tree adapter
 * plus a sidebar filter, exercised through the BUILD entry with real directory
 * fixtures (the same posture as the Mintlify/MkDocs tests). Pins: the sidebar
 * walk over Docusaurus's item shapes (bare doc-id string, `type: doc`/`ref`,
 * nested `type: category` with an optional category `link`), the
 * `type: autogenerated` fall-back to directory order, the MDX module-line
 * strip inherited from the base adapter, and the fail-loud posture on an
 * unresolvable sidebar config.
 *
 * A Docusaurus `sidebars.js`/`sidebars.ts` module must be EVALUATED (entries
 * can be computed), so — exactly like the injected `parseYaml` — the caller
 * loads it (`(await import(sidebarsPath)).default`) and hands the importer the
 * plain object; the importer owns the resolver. These tests therefore pass
 * plain sidebar objects, the same shape a loaded module yields.
 */

import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, test } from "bun:test";
import * as yaml from "js-yaml";

import {
  buildOkfBundle,
  createDocusaurusSource,
  NavManifestError,
  resolveDocusaurusSidebar,
  type ParseYaml,
} from "../src/index";

const parseYaml: ParseYaml = (raw) => yaml.load(raw);

const cleanups: string[] = [];
afterAll(async () => {
  await Promise.all(cleanups.map((dir) => rm(dir, { recursive: true, force: true })));
});

async function docsTreeOf(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "okf-docusaurus-"));
  cleanups.push(root);
  for (const [rel, content] of Object.entries(files)) {
    await mkdir(join(root, rel, ".."), { recursive: true });
    await writeFile(join(root, rel), content, "utf8");
  }
  return root;
}

/** A representative classic-preset sidebar: bare ids, a `type: doc`, a nested
 *  category with its own `link` landing page, and an external link (ignored). */
const REPRESENTATIVE_SIDEBARS = {
  docs: [
    "intro",
    { type: "doc", id: "getting-started" },
    {
      type: "category",
      label: "Guides",
      link: { type: "doc", id: "guides/index" },
      items: ["guides/config", { type: "ref", id: "guides/advanced" }],
    },
    { type: "link", label: "GitHub", href: "https://github.com/example" },
  ],
};

const REPRESENTATIVE_TREE: Record<string, string> = {
  "intro.mdx": [
    'import Tabs from "@theme/Tabs";',
    "",
    "# Intro",
    "",
    "Docusaurus intro prose that survives the module-line strip.",
  ].join("\n"),
  "getting-started.md": "Getting started prose that is long enough to count.",
  "guides/index.md": "Guides landing prose, definitely long enough here.",
  "guides/config.md": "Configuration guide prose, long enough to count.",
  "guides/advanced.md": "Advanced guide prose, long enough to count here.",
  // Present on disk, absent from the sidebar — must be skipped and COUNTED.
  "drafts/wip.md": "A draft page the sidebar never references, skipped.",
};

describe("createDocusaurusSource → buildOkfBundle", () => {
  test("collects only sidebar-reachable pages; off-sidebar pages are skipped and counted", async () => {
    const root = await docsTreeOf(REPRESENTATIVE_TREE);
    const { source, filter, sidebar } = await createDocusaurusSource({
      root,
      parseYaml,
      sidebars: REPRESENTATIVE_SIDEBARS,
    });

    expect(sidebar.pages.has("intro")).toBe(true);
    expect(sidebar.pages.has("guides/advanced")).toBe(true);
    const result = await buildOkfBundle(source, { prefix: "kb", filter, tags: ["docusaurus"] });
    expect(result.docs.map((d) => d.path)).toEqual([
      "kb/getting-started.md",
      "kb/guides/advanced.md",
      "kb/guides/config.md",
      "kb/guides.md",
      "kb/intro.md",
    ]);
    // drafts/wip.md declined by the sidebar filter.
    expect(result.stats.skipped.filtered).toBe(1);

    // The MDX module line is stripped by the base adapter's fence-aware strip.
    const intro = result.docs.find((d) => d.path === "kb/intro.md");
    expect(intro?.content).toContain("Docusaurus intro prose");
    expect(intro?.content).not.toContain("@theme/Tabs");

    // Deterministic rebuild: identical tree + sidebar → identical bytes.
    const again = await createDocusaurusSource({
      root,
      parseYaml,
      sidebars: REPRESENTATIVE_SIDEBARS,
    });
    const againBundle = await buildOkfBundle(again.source, {
      prefix: "kb",
      filter: again.filter,
      tags: ["docusaurus"],
    });
    expect(Buffer.from(againBundle.bytes).equals(Buffer.from(result.bytes))).toBe(true);
  });

  test("a type: autogenerated category expands to every doc under its dirName (directory-order fallback)", async () => {
    const root = await docsTreeOf({
      "intro.md": "Intro prose, long enough to count here nicely.",
      "reference/a.md": "Reference A prose, long enough to count here.",
      "reference/b.md": "Reference B prose, long enough to count here.",
      "reference/nested/c.md": "Reference nested C prose, long enough here.",
      "elsewhere/off.md": "Off page, not under the autogenerated dir, skipped.",
    });
    const { source, filter } = await createDocusaurusSource({
      root,
      parseYaml,
      sidebars: {
        docs: ["intro", { type: "autogenerated", dirName: "reference" }],
      },
    });
    const result = await buildOkfBundle(source, { prefix: "kb", filter });
    expect(result.docs.map((d) => d.path)).toEqual([
      "kb/intro.md",
      "kb/reference/a.md",
      "kb/reference/b.md",
      "kb/reference/nested/c.md",
    ]);
    expect(result.stats.skipped.filtered).toBe(1);
  });

  test("maps frontmatter title/description into the collected doc", async () => {
    const root = await docsTreeOf({
      "getting-started.md": [
        "---",
        'title: "Getting Started"',
        "description: How to start with Acme",
        "---",
        "Body prose that is long enough to count.",
      ].join("\n"),
    });
    const { source, filter } = await createDocusaurusSource({
      root,
      parseYaml,
      sidebars: { docs: ["getting-started"] },
    });
    const result = await buildOkfBundle(source, { prefix: "kb", filter });
    const doc = result.docs.find((d) => d.path === "kb/getting-started.md");
    expect(doc?.content).toContain('title: "Getting Started"');
    expect(doc?.content).toContain('description: "How to start with Acme"');
  });

  test("a custom extensions option keeps the filter's strip in sync — failure stays accurately attributed", async () => {
    const root = await docsTreeOf({
      "notes.markdown": "---\ntitle: Notes\n---\nCustom-extension page prose here.",
    });
    const { source, filter } = await createDocusaurusSource({
      root,
      parseYaml,
      sidebars: { docs: ["notes"] },
      extensions: [".markdown"],
    });
    // Strip synced to the effective set → the page passes the filter and the
    // build fails downstream naming it, not as a misattributed empty bundle.
    await expect(buildOkfBundle(source, { prefix: "kb", filter })).rejects.toThrow(
      /notes\.markdown/,
    );
  });

  test("a fully autogenerated root sidebar (dirName '.') collects the whole tree", async () => {
    const root = await docsTreeOf({
      "a.md": "Page A prose, long enough to count here nicely.",
      "sub/b.md": "Page B prose, long enough to count here nicely.",
    });
    const { source, filter } = await createDocusaurusSource({
      root,
      parseYaml,
      sidebars: { docs: [{ type: "autogenerated", dirName: "." }] },
    });
    const result = await buildOkfBundle(source, { prefix: "kb", filter });
    expect(result.docs.map((d) => d.path)).toEqual(["kb/a.md", "kb/sub/b.md"]);
  });
});

describe("resolveDocusaurusSidebar", () => {
  const treePaths = [
    "intro.mdx",
    "getting-started.md",
    "guides/index.md",
    "guides/config.md",
    "guides/advanced.md",
    "reference/api.md",
  ];

  test("walks every item shape and ignores link items and category labels", () => {
    const sidebar = resolveDocusaurusSidebar(REPRESENTATIVE_SIDEBARS, treePaths);
    expect([...sidebar.pages].sort()).toEqual([
      "getting-started",
      "guides/advanced",
      "guides/config",
      "guides/index",
      "intro",
    ]);
  });

  test("doc ids tolerate a leading slash and an explicit extension", () => {
    const sidebar = resolveDocusaurusSidebar(
      { docs: ["/getting-started", { type: "doc", id: "intro.mdx" }] },
      treePaths,
    );
    expect([...sidebar.pages].sort()).toEqual(["getting-started", "intro"]);
  });

  test("autogenerated dirName tolerates leading/trailing slashes and a ./ prefix", () => {
    for (const dirName of ["reference", "/reference/", "./reference", "reference//"]) {
      const sidebar = resolveDocusaurusSidebar(
        { docs: [{ type: "autogenerated", dirName }] },
        treePaths,
      );
      expect([...sidebar.pages].sort()).toEqual(["reference/api"]);
    }
  });

  test("multiple named sidebars union their reachable docs", () => {
    const sidebar = resolveDocusaurusSidebar(
      { docs: ["intro"], api: [{ type: "autogenerated", dirName: "reference" }] },
      treePaths,
    );
    expect([...sidebar.pages].sort()).toEqual(["intro", "reference/api"]);
  });

  test("a bare top-level sidebar array resolves the same as the map form", () => {
    const sidebar = resolveDocusaurusSidebar(
      ["intro", { type: "category", label: "Guides", items: ["guides/config"] }],
      treePaths,
    );
    expect([...sidebar.pages].sort()).toEqual(["guides/config", "intro"]);
  });

  test("a generated-index category link names no doc; only doc links and items do", () => {
    const sidebar = resolveDocusaurusSidebar(
      {
        docs: [
          "intro",
          {
            type: "category",
            label: "Guides",
            link: { type: "generated-index" },
            items: ["guides/config"],
          },
        ],
      },
      treePaths,
    );
    // The generated-index link contributed nothing (no source file); intro and
    // the category's item are the only reachable docs.
    expect([...sidebar.pages].sort()).toEqual(["guides/config", "intro"]);
  });
});

describe("fail-loud sidebar handling", () => {
  test("a non-object sidebars value → NavManifestError", () => {
    expect(() => resolveDocusaurusSidebar("nope", [])).toThrow(NavManifestError);
    expect(() => resolveDocusaurusSidebar(null, [])).toThrow(NavManifestError);
  });

  test("a typed doc/ref item with a missing or non-string id fails loud, never a silent drop", () => {
    // A typed item is unambiguously a doc reference; dropping it silently would
    // ship a partial bundle that never trips the zero-page guard.
    expect(() => resolveDocusaurusSidebar({ docs: [{ type: "doc" }] }, ["intro.md"])).toThrow(
      /missing or non-string "id"/,
    );
    expect(() =>
      resolveDocusaurusSidebar({ docs: [{ type: "ref", id: 123 }] }, ["intro.md"]),
    ).toThrow(NavManifestError);
    // Same for a `doc`-typed category link with a broken id.
    expect(() =>
      resolveDocusaurusSidebar(
        { docs: [{ type: "category", label: "G", link: { type: "doc" }, items: ["intro"] }] },
        ["intro.md"],
      ),
    ).toThrow(/missing or non-string "id"/);
  });

  test("a typed doc item whose id resolves to no doc path (empty/external) fails loud", () => {
    expect(() => resolveDocusaurusSidebar({ docs: [{ type: "doc", id: "" }] }, ["intro.md"])).toThrow(
      /resolves to no doc path/,
    );
    expect(() =>
      resolveDocusaurusSidebar({ docs: [{ type: "doc", id: "https://example.com" }] }, ["intro.md"]),
    ).toThrow(/resolves to no doc path/);
  });

  test("a sidebar that resolves to zero pages → NavManifestError, never a silent empty bundle", () => {
    expect(() =>
      resolveDocusaurusSidebar(
        { docs: [{ type: "link", href: "https://example.com", label: "Only Links" }] },
        ["intro.md"],
      ),
    ).toThrow(/no page paths/);
  });

  test("a type: autogenerated item with a missing or non-string dirName fails loud, even when other entries resolve", () => {
    // `intro` resolves, so docIds is non-empty — the zero-page guard would
    // mask the dropped directory. The fail-loud dirName check catches it.
    expect(() =>
      resolveDocusaurusSidebar({ docs: ["intro", { type: "autogenerated" }] }, [
        "intro.md",
        "reference/a.md",
      ]),
    ).toThrow(/missing or non-string "dirName"/);
  });

  test("an autogenerated dirName matching nothing on disk → NavManifestError", () => {
    expect(() =>
      resolveDocusaurusSidebar({ docs: [{ type: "autogenerated", dirName: "ghost" }] }, ["intro.md"]),
    ).toThrow(/no page paths/);
  });

  test("createDocusaurusSource surfaces the fail-loud resolver error", async () => {
    const root = await docsTreeOf({ "intro.md": "Intro prose, long enough to count." });
    await expect(
      createDocusaurusSource({ root, parseYaml, sidebars: { docs: [] } }),
    ).rejects.toThrow(NavManifestError);
  });
});
